#!/usr/bin/env node
// racingpoint/graphify-meta/build-meta.mjs
// "Map of maps" — reads every per-module graphify-out/graph.json and synthesises a meta-graph
// with one super-node per module + inter-module edges inferred from label overlap.
//
// Output:
//   meta-graph.json — machine-readable
//   meta.html       — interactive vis-network viz with drill-down links to each module's graph.html
//   META_REPORT.md  — summary + which modules are missing / stale
//
// Zero dependencies (uses bundled vis-network CDN in HTML).

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Resolve ROOT by walking up from script location looking for the ecosystem root.
// Works from both legacy `<ROOT>/graphify-meta/` and `<ROOT>/racecontrol/graphify-meta/`.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
function findEcosystemRoot(start) {
  let d = start;
  for (let i = 0; i < 6; i++) {
    if (fs.existsSync(path.join(d, 'racecontrol')) && fs.existsSync(path.join(d, 'racingpoint-admin'))) return d;
    const parent = path.dirname(d);
    if (parent === d) break;
    d = parent;
  }
  return null;
}
const ROOT = (process.env.GRAPHIFY_META_ROOT || findEcosystemRoot(__dirname) || 'C:/Users/bono/racingpoint').replace(/\\/g, '/');

// Registry: name → { repo_root, purpose, color, graph_path, html_path }
// Colors chosen from graphify palette for consistency.
const MODULES = [
  { id: 'racecontrol',       label: 'Racecontrol',       color: '#4E79A7', purpose: 'Core server + pod binaries (rc-agent, rc-sentry, kiosk, web, admin-api)' },
  { id: 'racingpoint-admin', label: 'Admin Panel',       color: '#E15759', purpose: 'Next.js staff dashboard at :3201' },
  { id: 'comms-link',        label: 'Comms Link',        color: '#59A14F', purpose: 'James↔Bono WS relay on Node.js' },
  { id: 'whatsapp-bot',      label: 'WhatsApp Bot',      color: '#F28E2B', purpose: 'Customer-facing WA bot (Claude API, Evolution API)' },
  { id: 'people-tracker',    label: 'People Tracker',    color: '#B07AA1', purpose: 'YOLOv8 entry/exit counter, FastAPI' },
  { id: 'marketing',         label: 'Marketing',         color: '#FF9DA7', purpose: 'Retention nudges, campaign logic' },
  { id: 'pod-agent',         label: 'pod-agent (legacy)',color: '#9C755F', purpose: 'Legacy Python pod-agent (predecessor to rc-agent)' },
  { id: 'rc-ops-mcp',        label: 'RC Ops MCP',        color: '#76B7B2', purpose: 'MCP server for ops queries' },
  // MCP sibling repos — registered daily via .claude.json.
  { id: 'racingpoint-mcp-calendar', label: 'MCP Calendar', color: '#A6CEE3', purpose: 'MCP server for Google Calendar' },
  { id: 'racingpoint-mcp-drive',    label: 'MCP Drive',    color: '#B2DF8A', purpose: 'MCP server for Google Drive' },
  { id: 'racingpoint-mcp-gmail',    label: 'MCP Gmail',    color: '#FB9A99', purpose: 'MCP server for Gmail' },
  { id: 'racingpoint-mcp-sheets',   label: 'MCP Sheets',   color: '#FDBF6F', purpose: 'MCP server for Google Sheets' },
];

// Sliced sub-modules of racecontrol. Generated by slice-submodules.mjs into
// racecontrol/graphify-out-<id>/graph.json. Optional — if slices.json is missing
// or stale the meta-map still works, just without child nodes.
const SLICE_PALETTE = ['#8CD17D', '#AECD8C', '#79706E', '#BAB0AC', '#D4A6C8', '#F1CE63', '#499894', '#86BCB6'];
const slicesManifestPath = path.join(__dirname, 'slices.json');
let SLICES = [];
if (fs.existsSync(slicesManifestPath)) {
  const manifest = JSON.parse(fs.readFileSync(slicesManifestPath, 'utf8'));
  SLICES = manifest.slices.map((s, i) => {
    // graph_path may be absolute (legacy) or ROOT-relative (v3+). Resolve to absolute.
    const resolveRel = p => p && (path.isAbsolute(p) ? p : path.join(ROOT, p));
    return {
      id: `rc.${s.id}`,
      label: s.label,
      color: SLICE_PALETTE[i % SLICE_PALETTE.length],
      purpose: s.purpose,
      parent: s.parent,
      graph_path_override: resolveRel(s.graph_path),
      html_path_override:  resolveRel(s.html_path),
    };
  });
}
MODULES.push(...SLICES);

// Load each module's graph (if present) + compute stats
const moduleStats = [];
for (const m of MODULES) {
  const gpath = m.graph_path_override || path.join(ROOT, m.id, 'graphify-out', 'graph.json');
  const hpath = m.html_path_override
    || (m.graph_path_override
          ? gpath.replace(/graph\.json$/, 'graph.html')
          : path.join(ROOT, m.id, 'graphify-out', 'graph.html'));
  if (!fs.existsSync(gpath)) {
    moduleStats.push({ ...m, status: 'MISSING', nodes: 0, edges: 0, communities: 0, top_labels: [], god_nodes: [] });
    continue;
  }
  const g = JSON.parse(fs.readFileSync(gpath, 'utf8'));
  const communities = new Set(g.nodes.map(n => n.community));

  // Top labels by degree (god nodes)
  const deg = new Map();
  const edges = g.links || g.edges || [];
  for (const e of edges) {
    const s = e.source || e.from; const t = e.target || e.to;
    deg.set(s, (deg.get(s)||0)+1);
    deg.set(t, (deg.get(t)||0)+1);
  }
  const byDeg = g.nodes
    .map(n => ({ id: n.id, label: n.label, norm: (n.norm_label || n.label || '').toLowerCase(), deg: deg.get(n.id)||0, sf: n.source_file }))
    .sort((a,b) => b.deg - a.deg);
  // Labels that appear in every Next.js / Rust / common framework project and are therefore
  // useless for overlap matching — their presence in two modules doesn't indicate coupling.
  const FRAMEWORK_STOPLIST = new Set([
    // Next.js
    'page.tsx', 'layout.tsx', 'route.ts', 'route.tsx', 'loading.tsx', 'error.tsx', 'not-found.tsx',
    'middleware.ts', 'middleware.tsx', 'globals.css', 'page.jsx', 'layout.jsx',
    // Generic config + tooling
    'index.ts', 'index.tsx', 'index.js', 'index.mjs', 'index.jsx',
    'package.json', 'tsconfig.json', 'next.config.ts', 'next.config.js', 'next.config.mjs',
    'vite.config.ts', 'vitest.config.ts', 'eslint.config.mjs', 'eslint.config.js',
    'tailwind.config.ts', 'tailwind.config.js', 'postcss.config.mjs', 'postcss.config.js',
    'playwright.config.ts', 'jest.config.ts', 'jest.config.js',
    // Rust
    'mod.rs', 'lib.rs', 'main.rs', 'build.rs', 'cargo.toml', 'cargo.lock',
    // Generic
    '.gitignore', '.env', '.env.local', '.env.production', 'readme.md', 'license',
    // Tier-2 convention names: identifiers that appear across many unrelated codebases
    // with no shared semantics. Session-3 found rc.web↔racingpoint-admin coupled via
    // `metrics.ts / get() / handledelete()` — those are dashboard boilerplate, not coupling.
    'metrics.ts', 'metrics.js', 'utils.ts', 'utils.js', 'types.ts', 'types.js',
    'constants.ts', 'constants.js', 'helpers.ts', 'helpers.js', 'config.ts', 'config.js',
    'get()', 'post()', 'put()', 'patch()', 'delete()', 'head()', 'options()',
    'render()', 'handle()', 'main()', 'init()', 'start()', 'stop()', 'run()',
    'handledelete()', 'handleget()', 'handlepost()', 'handleput()',
    'setstate()', 'setloading()', 'seterror()', 'ondelete()', 'onsubmit()',
    'fetch()', 'load()', 'save()', 'reset()', 'close()', 'open()',
    // Common Python stubs
    '__init__.py', '__main__.py', 'setup.py', 'conftest.py', 'requirements.txt',
  ]);
  // Exclude stoplist labels AND bare builtin method calls like '.push()' / '.collect()'
  // that have zero semantic weight when computing inter-module overlap.
  const isUsefulLabel = lbl => lbl && lbl.length > 3 && !FRAMEWORK_STOPLIST.has(lbl) && !lbl.startsWith('.');
  const top_labels = [...new Set(byDeg.map(x => x.norm).filter(isUsefulLabel))].slice(0, 30);
  const god_nodes = byDeg.slice(0, 10).map(x => ({ label: x.label, deg: x.deg }));
  const distinct_files = new Set(g.nodes.map(n => (n.source_file||'').replace(/\\/g,'/')).filter(Boolean)).size;

  moduleStats.push({
    ...m,
    status: 'OK',
    nodes: g.nodes.length,
    edges: edges.length,
    communities: communities.size,
    distinct_files,
    top_labels,
    god_nodes,
    graph_path: gpath,
    html_path: fs.existsSync(hpath) ? hpath : null,
    has_communities_dir: fs.existsSync(path.join(ROOT, m.id, 'graphify-out', 'communities')),
  });
}

// Compute inter-module edges — two types:
// (a) API-URL edges from api-edges.json (HIGH confidence — real fetch/axios to racecontrol routes)
// (b) Label-overlap (LOW confidence — noisy due to generic names like get/load/main)
const metaLinks = [];

// (a) API-URL edges
const apiEdgesPath = path.join(__dirname, 'api-edges.json');
if (fs.existsSync(apiEdgesPath)) {
  const api = JSON.parse(fs.readFileSync(apiEdgesPath, 'utf8'));
  // Aggregate per (from,to) pair with url_fragments list
  const byPair = new Map();
  for (const e of api.edges) {
    const key = `${e.from}|${e.to}`;
    if (!byPair.has(key)) byPair.set(key, []);
    byPair.get(key).push(e.url_fragment);
  }
  for (const [key, frags] of byPair) {
    const [from, to] = key.split('|');
    metaLinks.push({
      source: from, target: to,
      weight: frags.length,
      type: 'api-call',
      url_fragments: frags,
    });
  }
}

// Alias map: scanners with finer slice granularity emit ids that don't exist as
// meta-map nodes. Fold them back to the umbrella `racecontrol` module.
// - `racecontrol.crates` (ws/db scanners) → racecontrol
// - `racecontrol.server` (fs scanner's crates/racecontrol) → racecontrol
// rc.rc-agent and rc.rc-sentry ARE registered slice nodes — keep them as-is.
const MODULE_ALIAS = {
  'racecontrol.crates': 'racecontrol',
  'racecontrol.server': 'racecontrol',
};
const aliasOf = id => MODULE_ALIAS[id] || id;

// (a2) DB shared-table edges
const dbEdgesPath = path.join(__dirname, 'db-edges.json');
if (fs.existsSync(dbEdgesPath)) {
  const db = JSON.parse(fs.readFileSync(dbEdgesPath, 'utf8'));
  for (const e of db.edges) {
    const src = aliasOf(e.from), tgt = aliasOf(e.to);
    if (src === tgt) continue;  // self-loop after aliasing
    // Threshold lowered to 1: stopword filter now catches prose/import false positives
    // so a single genuine shared table is already meaningful coupling (admin <-> rc via
    // `employees`, comms-link <-> whatsapp-bot via `messages`).
    if (e.weight < 1) continue;
    metaLinks.push({
      source: src, target: tgt,
      weight: e.weight,
      type: 'shared-db-table',
      shared_tables: e.shared_tables.slice(0, 5).map(s => s.table),
    });
  }
}

// (a3) WS shared-variant edges. Lowered threshold to >=1 because the slice-aware
// scanner now produces fine-grained edges (kiosk<->backend: 1 variant = real signal).
const wsEdgesPath = path.join(__dirname, 'ws-edges.json');
if (fs.existsSync(wsEdgesPath)) {
  const ws = JSON.parse(fs.readFileSync(wsEdgesPath, 'utf8'));
  for (const e of ws.edges) {
    const src = aliasOf(e.from), tgt = aliasOf(e.to);
    if (src === tgt) continue;
    if (e.weight < 1) continue;
    metaLinks.push({
      source: src, target: tgt,
      weight: e.weight,
      type: 'shared-ws-variant',
      shared_variants: e.shared_variants.slice(0, 5),
    });
  }
}

// (a4b) Filesystem-sentinel edges — modules that reference the same path literal
// (MAINTENANCE_MODE, GRACEFUL_RELAUNCH, ota-in-progress.flag, shared config dir).
// This channel was added in round 7 after git co-change mining revealed rc-agent ↔
// rc-sentry were shipping together 15x due to file-sentinel IPC that api/db/ws missed.
const fsEdgesPath = path.join(__dirname, 'fs-edges.json');
if (fs.existsSync(fsEdgesPath)) {
  const fsE = JSON.parse(fs.readFileSync(fsEdgesPath, 'utf8'));
  for (const e of fsE.edges) {
    const src = aliasOf(e.from), tgt = aliasOf(e.to);
    if (src === tgt) continue;
    if (e.weight < 2) continue;  // 1 shared path = likely CWD-ish noise; 2+ = real
    metaLinks.push({
      source: src, target: tgt,
      weight: e.weight,
      type: 'shared-fs-path',
      shared_paths: e.shared_paths.slice(0, 3).map(s => s.path.split('/').slice(-2).join('/')),
    });
  }
}

// (a4c) Git co-change edges — coincidence or real coupling the scanners missed.
// Only include pairs above the MIN_COMMITS threshold AND that have NO other channel
// edge (to avoid double-counting known coupling).
const cochangePath = path.join(__dirname, 'cochange-edges.json');
if (fs.existsSync(cochangePath)) {
  const cc = JSON.parse(fs.readFileSync(cochangePath, 'utf8'));
  // Only `hidden_coupling` — pairs already explained by other channels are redundant
  for (const h of cc.hidden_coupling) {
    if (h.cochange_commits < 10) continue;  // filter package.json-bump noise
    const src = aliasOf(h.module_a), tgt = aliasOf(h.module_b);
    if (src === tgt) continue;
    // Double-check: did we just add an fs-path edge for this pair in this same run?
    const alreadyExplained = metaLinks.some(e =>
      (e.source === src && e.target === tgt) || (e.source === tgt && e.target === src)
    );
    if (alreadyExplained) continue;
    metaLinks.push({
      source: src, target: tgt,
      weight: h.cochange_commits,
      type: 'co-change',
      top_file_pair: h.top_file_pairs[0]?.pair,
    });
  }
}

// (a4) Parent-contains edges — make slice hierarchy visible. Low weight so they don't
// dominate the layout; dashed styling handled in viz.
for (const s of SLICES) {
  metaLinks.push({
    source: s.parent, target: s.id,
    weight: 1,
    type: 'contains',
    label: `parent`,
  });
}

// (b) Label-overlap edges (filtered: only with 3+ overlap AND not already covered by api-call)
const apiPairs = new Set(metaLinks.map(e => `${e.source}|${e.target}`));
for (let i = 0; i < moduleStats.length; i++) {
  for (let j = i + 1; j < moduleStats.length; j++) {
    const A = moduleStats[i], B = moduleStats[j];
    if (A.status !== 'OK' || B.status !== 'OK') continue;
    if (apiPairs.has(`${A.id}|${B.id}`) || apiPairs.has(`${B.id}|${A.id}`)) continue;
    const setA = new Set(A.top_labels.filter(x => x && x.length > 3));
    const overlap = B.top_labels.filter(x => setA.has(x));
    if (overlap.length >= 3) {
      metaLinks.push({
        source: A.id, target: B.id,
        weight: overlap.length,
        type: 'label-overlap',
        shared_labels: overlap.slice(0, 5),
      });
    }
  }
}

// Persist meta-graph JSON
const metaOut = __dirname;
const metaGraph = {
  directed: false,
  generated_at: new Date().toISOString(),
  modules: moduleStats.map(m => {
    const { top_labels, ...public_fields } = m; // drop top_labels from public output — noisy
    return public_fields;
  }),
  edges: metaLinks,
};
fs.writeFileSync(path.join(metaOut, 'meta-graph.json'), JSON.stringify(metaGraph, null, 2));

// Generate interactive HTML with vis-network
const visNodes = moduleStats.map(m => ({
  id: m.id,
  label: `${m.label}\n(${m.status === 'OK' ? `${m.nodes} nodes` : 'NOT SCANNED'})`,
  color: m.status === 'OK' ? { background: m.color, border: m.color } : { background: '#333', border: '#555' },
  font: { color: '#e0e0e0', size: 14 },
  size: m.status === 'OK' ? Math.min(20 + Math.sqrt(m.nodes) * 1.5, 80) : 15,
  title: m.status === 'OK'
    ? `${m.label}\n${m.purpose}\n${m.nodes} nodes · ${m.edges} edges · ${m.communities} communities\nTop: ${m.god_nodes.slice(0,3).map(g=>g.label).join(', ')}`
    : `${m.label} — NOT SCANNED\n${m.purpose}\n(run /graphify in ${m.id}/)`,
  href: m.html_path ? path.relative(metaOut, m.html_path).replace(/\\/g, '/') : null,
  status: m.status,
}));
const EDGE_STYLE = {
  'api-call':          { color: '#59A14F', dashes: false, arrow: true,  label: 'HTTP API call' },
  'shared-db-table':   { color: '#F1CE63', dashes: false, arrow: false, label: 'shared DB table(s)' },
  'shared-ws-variant': { color: '#E15759', dashes: false, arrow: false, label: 'shared WS variant(s)' },
  'shared-fs-path':    { color: '#B07AA1', dashes: false, arrow: false, label: 'shared filesystem path(s)' },
  'co-change':         { color: '#D4A6C8', dashes: true,  arrow: false, label: 'git co-change (unexplained)' },
  'label-overlap':     { color: '#6a7aaa', dashes: true,  arrow: false, label: 'shared top-30 label(s)' },
  'contains':          { color: '#555',    dashes: true,  arrow: false, label: 'contains (slice)' },
};
const visEdges = metaLinks.map(e => {
  const style = EDGE_STYLE[e.type] || EDGE_STYLE['label-overlap'];
  const detailPart = e.url_fragments ? e.url_fragments.join(', ')
                   : e.shared_tables ? e.shared_tables.join(', ')
                   : e.shared_variants ? e.shared_variants.join(', ')
                   : e.shared_labels ? e.shared_labels.join(', ')
                   : '';
  return {
    from: e.source, to: e.target,
    width: Math.min(1 + Math.log2(e.weight + 1), 6),
    title: `${style.label} · ${e.weight}${detailPart ? ': ' + detailPart : ''}`,
    color: { color: style.color, opacity: style.dashes ? 0.4 : 0.9 },
    dashes: style.dashes,
    arrows: style.arrow ? { to: { enabled: true, scaleFactor: 0.6 } } : undefined,
  };
});

const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>RacingPoint — Map of Maps</title>
<script src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #0f0f1a; color: #e0e0e0; font-family: -apple-system, Segoe UI, sans-serif; display: flex; height: 100vh; overflow: hidden; }
  #graph { flex: 1; }
  #sidebar { width: 340px; background: #1a1a2e; border-left: 1px solid #2a2a4e; padding: 16px; overflow-y: auto; }
  #sidebar h1 { font-size: 16px; margin-bottom: 8px; }
  #sidebar .meta { color: #999; font-size: 12px; margin-bottom: 14px; }
  .module { padding: 10px; border-radius: 6px; background: #222; margin-bottom: 8px; cursor: pointer; border-left: 4px solid #444; font-size: 12px; }
  .module:hover { background: #2a2a4e; }
  .module h3 { font-size: 13px; margin-bottom: 4px; }
  .module .purpose { color: #aaa; font-size: 11px; margin-bottom: 6px; }
  .module .stats { color: #888; font-size: 11px; }
  .module.missing { opacity: 0.5; border-left-color: #555; }
  .module.missing .stats::before { content: "Not scanned — "; color: #e15759; }
  a.open-module { display: inline-block; margin-top: 6px; color: #4E79A7; font-size: 11px; text-decoration: none; }
  a.open-module:hover { text-decoration: underline; }
  .edges { margin-top: 14px; }
  .edges h2 { font-size: 12px; color: #aaa; text-transform: uppercase; margin-bottom: 6px; letter-spacing: 0.05em; }
  .edge-item { padding: 4px 8px; background: #181828; margin-bottom: 3px; border-radius: 3px; font-size: 11px; color: #bbb; }
  .legend { margin-top: 14px; padding: 8px; background: #181828; border-radius: 4px; font-size: 11px; }
  .legend h2 { font-size: 12px; color: #aaa; text-transform: uppercase; margin-bottom: 6px; letter-spacing: 0.05em; }
  .legend .row { display: flex; align-items: center; margin: 3px 0; gap: 8px; }
  .legend .swatch { width: 24px; height: 2px; border-radius: 1px; flex-shrink: 0; }
  .legend .swatch.dashed { background: repeating-linear-gradient(to right, currentColor 0 3px, transparent 3px 6px); height: 2px; }
  .legend .label { color: #bbb; }
</style></head>
<body>
<div id="graph"></div>
<div id="sidebar">
  <h1>RacingPoint — Map of Maps</h1>
  <div class="meta">${moduleStats.filter(m=>m.status==='OK').length} of ${moduleStats.length} modules scanned · Regenerated ${new Date().toISOString().slice(0,16)}Z</div>
  ${moduleStats.map(m => `
    <div class="module ${m.status==='MISSING'?'missing':''}" data-id="${m.id}">
      <h3 style="color:${m.color}">${m.label}</h3>
      <div class="purpose">${m.purpose}</div>
      <div class="stats">${m.status==='OK'?`${m.nodes} nodes · ${m.edges} edges · ${m.communities} communities`:'no graphify-out/ in this repo'}</div>
      ${m.html_path ? `<a class="open-module" href="file:///${path.resolve(m.html_path).replace(/\\\\/g,'/')}" target="_blank">open ${m.id}/graphify-out/graph.html →</a>` : ''}
    </div>
  `).join('')}
  <div class="edges">
    <h2>Inter-module overlaps (top-30 label matches)</h2>
    ${metaLinks.filter(e => e.type !== 'contains').sort((a,b)=> {
      const rank = { 'api-call': 4000, 'shared-ws-variant': 3000, 'shared-db-table': 2000, 'shared-fs-path': 1000, 'co-change': 500, 'label-overlap': 0 };
      return (rank[b.type]||0) + b.weight - (rank[a.type]||0) - a.weight;
    }).slice(0,25).map(e => {
      const style = {
        'api-call':          ['#59A14F', 'API'],
        'shared-db-table':   ['#F1CE63', 'DB'],
        'shared-ws-variant': ['#E15759', 'WS'],
        'shared-fs-path':    ['#B07AA1', 'FS'],
        'co-change':         ['#D4A6C8', 'git'],
        'label-overlap':     ['#888',    'lbl'],
      }[e.type] || ['#888', '?'];
      const detail = e.url_fragments   ? e.url_fragments.join(', ')
                   : e.shared_tables   ? e.shared_tables.join(', ')
                   : e.shared_variants ? e.shared_variants.join(', ')
                   : e.shared_paths    ? e.shared_paths.join(', ')
                   : e.top_file_pair   ? e.top_file_pair
                   : e.shared_labels   ? e.shared_labels.join(', ')
                   : '';
      return `<div class="edge-item"><span style="color:${style[0]}">${style[1]}</span> <b>${e.source}</b> → <b>${e.target}</b> · ${e.weight} · ${detail}</div>`;
    }).join('')}
    ${metaLinks.length === 0 ? '<div class="edge-item"><em>No label overlap detected between scanned modules.</em></div>' : ''}
  </div>
  <div class="legend">
    <h2>Edge legend</h2>
    <div class="row"><div class="swatch" style="background:#59A14F;color:#59A14F"></div><span class="label">api-call — HTTP /api/ endpoint</span></div>
    <div class="row"><div class="swatch" style="background:#E15759;color:#E15759"></div><span class="label">shared-ws-variant — same WS enum variant referenced</span></div>
    <div class="row"><div class="swatch" style="background:#F1CE63;color:#F1CE63"></div><span class="label">shared-db-table — same SQL table read/written</span></div>
    <div class="row"><div class="swatch" style="background:#B07AA1;color:#B07AA1"></div><span class="label">shared-fs-path — same filesystem sentinel / config</span></div>
    <div class="row"><div class="swatch dashed" style="color:#D4A6C8"></div><span class="label">co-change — git history coupling (no scanner edge)</span></div>
    <div class="row"><div class="swatch dashed" style="color:#6a7aaa"></div><span class="label">label-overlap — shared top-30 names (weak signal)</span></div>
    <div class="row"><div class="swatch dashed" style="color:#555"></div><span class="label">contains — slice of parent module</span></div>
  </div>
</div>
<script>
const nodes = new vis.DataSet(${JSON.stringify(visNodes)});
const edges = new vis.DataSet(${JSON.stringify(visEdges)});
const net = new vis.Network(document.getElementById('graph'), { nodes, edges }, {
  physics: { enabled: true, barnesHut: { gravitationalConstant: -8000, springConstant: 0.04 } },
  interaction: { hover: true },
  nodes: { shape: 'dot', borderWidth: 2 },
  edges: { smooth: { enabled: true, type: 'dynamic' } },
});
net.on('doubleClick', params => {
  if (!params.nodes.length) return;
  const n = nodes.get(params.nodes[0]);
  if (n.href) window.open(n.href, '_blank');
});
document.querySelectorAll('.module').forEach(el => {
  el.addEventListener('click', () => {
    const id = el.dataset.id;
    net.focus(id, { scale: 1.2, animation: true });
  });
});
</script>
</body></html>`;

fs.writeFileSync(path.join(metaOut, 'meta.html'), html);

// Markdown report
const reportLines = [];
reportLines.push(`# Map of Maps — RacingPoint ecosystem`);
reportLines.push(``);
reportLines.push(`Generated: ${new Date().toISOString()}`);
reportLines.push(``);
reportLines.push(`${moduleStats.filter(m=>m.status==='OK').length} of ${moduleStats.length} modules scanned.`);
reportLines.push(``);
reportLines.push(`## Modules`);
reportLines.push(``);
reportLines.push(`| Module | Status | Nodes | Edges | Communities | Graph path |`);
reportLines.push(`|---|---|---|---|---|---|`);
for (const m of moduleStats) {
  const gp = m.graph_path ? m.graph_path.replace(ROOT + '/', '') : '—';
  reportLines.push(`| ${m.label} | ${m.status} | ${m.nodes || '—'} | ${m.edges || '—'} | ${m.communities || '—'} | \`${gp}\` |`);
}
reportLines.push(``);
reportLines.push(`## Inter-module overlap (label-based heuristic)`);
reportLines.push(``);
if (metaLinks.length === 0) {
  reportLines.push(`*No label overlap detected among scanned modules.*`);
} else {
  reportLines.push(`| Type | From | To | Weight | Detail |`);
  reportLines.push(`|---|---|---|---|---|`);
  const rank = { 'api-call': 3000, 'shared-ws-variant': 2000, 'shared-db-table': 1000, 'label-overlap': 0 };
  const reportableLinks = metaLinks.filter(e => e.type !== 'contains');
  for (const e of reportableLinks.sort((a,b) => (rank[b.type]||0)+b.weight - (rank[a.type]||0)-a.weight)) {
    const detail = e.url_fragments ? e.url_fragments.map(f => `/api/${f}`).join(', ')
                 : e.shared_tables ? e.shared_tables.join(', ')
                 : e.shared_variants ? e.shared_variants.join(', ')
                 : (e.shared_labels || []).join(', ');
    reportLines.push(`| ${e.type || 'label-overlap'} | ${e.source} | ${e.target} | ${e.weight} | ${detail} |`);
  }
}
reportLines.push(``);
reportLines.push(`## Missing scans`);
reportLines.push(``);
const missing = moduleStats.filter(m => m.status === 'MISSING');
if (missing.length === 0) {
  reportLines.push(`*All modules scanned.*`);
} else {
  for (const m of missing) {
    reportLines.push(`- **${m.label}** — \`cd ${m.id} && /graphify .\`  _(${m.purpose})_`);
  }
}
reportLines.push(``);

// NEW: low-density + missing-HTML warnings. Same-session gap detection.
// Tightened: flag either low-density OR very small (< 10 nodes total even if 1 file).
// rc-ops-mcp has 2 nodes / 1 file = ratio 2.0 — not low-density — but 2 nodes is
// clearly degenerate for a 191-line MCP server.
const lowDensity = moduleStats.filter(m =>
  m.status === 'OK' && (
    (m.distinct_files > 0 && (m.nodes / m.distinct_files) < 0.5 && m.nodes < 20)
    || (m.nodes > 0 && m.nodes < 10)
  )
);
const missingHtml = moduleStats.filter(m => m.status === 'OK' && !m.html_path);
if (lowDensity.length || missingHtml.length) {
  reportLines.push(`## Warnings`);
  reportLines.push(``);
  if (lowDensity.length) {
    reportLines.push(`### Low-density graphs (likely incomplete graphify scan)`);
    reportLines.push(``);
    reportLines.push(`Modules with < 0.5 nodes/file AND < 20 total nodes — graphify may have auto-skipped due to small corpus. Re-run with \`--mode deep\` to force full extraction.`);
    reportLines.push(``);
    for (const m of lowDensity) {
      reportLines.push(`- **${m.label}** — ${m.nodes} nodes across ${m.distinct_files} files. Suggested: \`cd ${m.id} && /graphify . --mode deep\``);
    }
    reportLines.push(``);
  }
  if (missingHtml.length) {
    reportLines.push(`### Missing graph.html (no drill-down link in meta.html)`);
    reportLines.push(``);
    reportLines.push(`Graph HTML viewer is missing. Small graphs (< 1000 nodes) likely had graphify run without viz; very large graphs (> 5000 nodes) trigger graphify's auto-skip.`);
    reportLines.push(``);
    for (const m of missingHtml) {
      const reason = m.nodes > 5000 ? 'graphify auto-skips > 5000 nodes'
                   : m.nodes === 0 ? 'no graph.json'
                   : 'graphify ran without HTML output';
      reportLines.push(`- **${m.label}** (${m.nodes} nodes) — ${reason}. Re-run: \`cd ${m.id} && /graphify .\` (small) or emit lightweight viewer (large).`);
    }
    reportLines.push(``);
  }
}
reportLines.push(`## How to use`);
reportLines.push(``);
reportLines.push(`- **meta.html** — visual map-of-maps. Double-click a node to open that module's own graph.html.`);
reportLines.push(`- **meta-graph.json** — machine-readable: consume with any graphify-compatible tool.`);
reportLines.push(`- **Regenerate:** \`node graphify-meta/build-meta.mjs\`. No cost, milliseconds — just re-reads existing module graphs.`);
reportLines.push(``);

fs.writeFileSync(path.join(metaOut, 'META_REPORT.md'), reportLines.join('\n'));

// Console summary
console.log(`Meta-map built → ${metaOut}/`);
console.log(`  meta.html         (interactive)`);
console.log(`  meta-graph.json   (machine-readable)`);
console.log(`  META_REPORT.md    (summary)`);
console.log(``);
console.log(`Modules:`);
for (const m of moduleStats) {
  console.log(`  ${m.status === 'OK' ? 'OK  ' : 'MISS'} ${m.label.padEnd(22)} ${m.status === 'OK' ? `${m.nodes} nodes · ${m.communities} communities` : 'no graphify-out/'}`);
}
console.log(``);
if (metaLinks.length) {
  const consoleRank = { 'api-call': 3000, 'shared-ws-variant': 2000, 'shared-db-table': 1000, 'label-overlap': 0 };
  const badgeFor = t => ({ 'api-call':'API ', 'shared-db-table':'DB  ', 'shared-ws-variant':'WS  ', 'label-overlap':'lbl ', 'contains':'prnt' }[t] || '??? ');
  console.log(`Inter-module edges (top 10, excluding parent-contains):`);
  const nonContain = metaLinks.filter(e => e.type !== 'contains');
  for (const e of nonContain.sort((a,b)=> (consoleRank[b.type]||0)+b.weight - (consoleRank[a.type]||0)-a.weight).slice(0,10)) {
    const detail = (e.url_fragments || e.shared_tables || e.shared_variants || e.shared_labels || []).slice(0,3).join(', ');
    console.log(`  ${badgeFor(e.type)} ${e.source.padEnd(20)} -> ${e.target.padEnd(20)}  w=${e.weight}  [${detail}]`);
  }
} else {
  console.log(`No inter-module edges detected.`);
}
