//! MIRROR of the Captain-PINNED (2026-06-01) license_heartbeat canonical recipe.
//!
//! CANONICAL HOME = `packages/contracts` (`license.yaml` + `src/license.ts`) —
//! Replit-owned, parity-gated source of truth. This test + the generator
//! (`tests/golden/gen-heartbeat-golden-vector.mjs`) MIRROR it and MUST NOT drift.
//! (Same ownership precedent as `ReleaseManifest` ← `release.ts`.)
//!
//! HARD GATE (Replit 2026-06-01): the B9 ed25519 key is NOT generated until the
//! Captain ratifies the AUTH-MEMO-1 rule #5 packet. So this scaffold pins
//! STRUCTURE + canonical BYTES + LENGTH only — NO key material, NO signatures.
//! Signature-axis verification lands at INC-7 with the real key (the ReleaseManifest
//! vectors already prove the ed25519 verify mechanism). The fixture is fully
//! deterministic.
//!
//! Recipe (= `packages/contracts` `canonicalJson()`): compact JSON, struct-
//! DECLARATION field order, `signature` excluded, `feature_opt_in` an OPEN
//! Record<string,boolean> with keys sorted (BTreeMap → sorted for free) always
//! present, `issued_at`/`valid_until` = Unix ms. The 200-body envelope is
//! `SignedLicenseHeartbeat { license_heartbeat, signature, next_refresh_after }`;
//! only `license_heartbeat` (the 7 fields below) is signed — the test models that.
//!
//! Grounded carry-ins: A1 `feature_opt_in` = boolean (capability-manifest
//! `FeatureOptInMatrix`); A2 `machine_fingerprint` = composite sha256-hex in the
//! payload, components in the claim request (threat_model Q-INSTALLER-32 / R-135).
//!
//! When INC-7 lands (per-PR Captain auth), this type graduates to `src/heartbeat.rs`
//! and gains real-key signature verification. Regenerate the fixture with:
//!   node crates/rc-installer/tests/golden/gen-heartbeat-golden-vector.mjs

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

const GOLDEN: &str = include_str!("golden/license-heartbeat-golden.json");

/// Frozen spec anchors — NOT regenerated by the generator. The exact canonical
/// signed bytes for the pinned production / trial vectors. If the recipe drifts
/// (field order/format/sort/kid), `canonical_signed_bytes` diverges from these even
/// after a fixture regenerate, so a silent recipe change fails here. (Production is
/// 284 bytes, trial 243 — byte-length is fingerprint-value-independent.)
const EXPECTED_PRODUCTION_CANONICAL: &str = r#"{"tenant_id":"rp-hyd","machine_fingerprint":"f0e1d2c3b4a5968778695a4b3c2d1e0f00112233445566778899aabbccddeeff","issued_at":1748649600000,"valid_until":1748653200000,"signing_key_id":"rc-hb-test-001","license_class":"production","feature_opt_in":{"multiplayer":true,"telemetry":false}}"#;
const EXPECTED_TRIAL_CANONICAL: &str = r#"{"tenant_id":"rp-hyd","machine_fingerprint":"1a2b3c4d5e6f70819293a4b5c6d7e8f9000102030405060708090a0b0c0d0e0f","issued_at":1748649600000,"valid_until":1748653200000,"signing_key_id":"rc-hb-test-001","license_class":"trial","feature_opt_in":{}}"#;

/// Test-local mirror of the PINNED `license_heartbeat` SIGNED PAYLOAD (the 7 signed
/// fields; `signature` is a 200-body sibling and absent here per the hard gate).
/// Graduates to `src/heartbeat.rs` at INC-7.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct LicenseHeartbeat {
    tenant_id: String,
    machine_fingerprint: String,
    issued_at: u64,
    valid_until: u64,
    signing_key_id: String,
    license_class: String,
    /// OPEN Record<string,boolean>; canonicalizes with SORTED keys (BTreeMap).
    feature_opt_in: BTreeMap<String, bool>,
}

/// Borrowing view that serializes the signed payload in declaration order — the
/// bytes the ed25519 signature WILL cover (at ceremony). Same pattern as
/// `src/manifest.rs::CanonicalManifest` (not `serde_json::Value` which alphabetizes).
#[derive(Serialize)]
struct CanonicalHeartbeat<'a> {
    tenant_id: &'a str,
    machine_fingerprint: &'a str,
    issued_at: u64,
    valid_until: u64,
    signing_key_id: &'a str,
    license_class: &'a str,
    feature_opt_in: &'a BTreeMap<String, bool>,
}

impl LicenseHeartbeat {
    /// The exact bytes the ed25519 signature covers: the 7 signed fields, compact
    /// JSON, struct-declaration order. MUST stay byte-identical to the
    /// packages/contracts canonicalizer.
    fn canonical_signed_bytes(&self) -> Vec<u8> {
        let canonical = CanonicalHeartbeat {
            tenant_id: &self.tenant_id,
            machine_fingerprint: &self.machine_fingerprint,
            issued_at: self.issued_at,
            valid_until: self.valid_until,
            signing_key_id: &self.signing_key_id,
            license_class: &self.license_class,
            feature_opt_in: &self.feature_opt_in,
        };
        serde_json::to_vec(&canonical).expect("canonical serialize")
    }
}

fn fixture() -> serde_json::Value {
    serde_json::from_str(GOLDEN).expect("parse golden fixture")
}

fn heartbeat_of(v: &serde_json::Value) -> LicenseHeartbeat {
    serde_json::from_value(v["license_heartbeat"].clone()).expect("license_heartbeat deserializes")
}

/// Every vector: Rust canonical bytes are byte-identical to the TS canonicalizer
/// AND the recorded byte length matches. Covers production (non-empty
/// feature_opt_in) and trial (empty) — both license classes, both map shapes.
#[test]
fn all_vectors_byte_parity_and_length() {
    let f = fixture();
    let vectors = f["vectors"].as_array().expect("vectors array");
    assert!(vectors.len() >= 2, "need >=2 vectors (production + trial)");
    let (mut saw_production, mut saw_trial) = (false, false);
    for v in vectors {
        let label = v["label"].as_str().unwrap_or("?");
        let hb = heartbeat_of(v);
        let bytes = hb.canonical_signed_bytes();
        assert_eq!(
            hex::encode(&bytes),
            v["canonical_bytes_hex"].as_str().unwrap(),
            "[{label}] Rust canonical bytes diverged from the TS canonicalizer"
        );
        assert_eq!(
            bytes.len() as u64,
            v["canonical_byte_len"].as_u64().unwrap(),
            "[{label}] canonical byte length diverged"
        );
        match hb.license_class.as_str() {
            "production" => saw_production = true,
            "trial" => saw_trial = true,
            other => panic!("[{label}] unexpected license_class {other}"),
        }
    }
    assert!(saw_production && saw_trial, "vectors must cover both production and trial");
}

/// Frozen spec anchor: production canonical bytes == the hardcoded constant AND are
/// 284 bytes (Replit's pinned production length) — catches a silent recipe change.
#[test]
fn production_canonical_matches_frozen_spec_anchor() {
    let f = fixture();
    let v = f["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| heartbeat_of(v).license_class == "production")
        .expect("a production vector");
    let bytes = heartbeat_of(v).canonical_signed_bytes();
    assert_eq!(bytes, EXPECTED_PRODUCTION_CANONICAL.as_bytes(), "production canonical drifted from the frozen spec anchor");
    assert_eq!(bytes.len(), 284, "production canonical must be 284 bytes (Replit-pinned length)");
}

/// Frozen spec anchor: trial canonical bytes == the hardcoded constant AND are 243
/// bytes (Replit's pinned trial length). Trial uses the SAME kid as production
/// (rc-hb-test-001) per the pinned vector.
#[test]
fn trial_canonical_matches_frozen_spec_anchor() {
    let f = fixture();
    let v = f["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| heartbeat_of(v).license_class == "trial")
        .expect("a trial vector");
    let bytes = heartbeat_of(v).canonical_signed_bytes();
    assert_eq!(bytes, EXPECTED_TRIAL_CANONICAL.as_bytes(), "trial canonical drifted from the frozen spec anchor");
    assert_eq!(bytes.len(), 243, "trial canonical must be 243 bytes (Replit-pinned length)");
}

/// Signature-free non-vacuity (payload axis): the canonicalizer is content-sensitive
/// — mutating a signed field changes the canonical bytes (it is not a constant).
/// (Signature verification itself is deferred to the key ceremony / INC-7.)
#[test]
fn canonical_bytes_are_content_sensitive() {
    let f = fixture();
    let v = f["vectors"].as_array().unwrap().iter().find(|v| heartbeat_of(v).license_class == "production").unwrap();
    let original = heartbeat_of(v).canonical_signed_bytes();
    let mut mutated = heartbeat_of(v);
    mutated.valid_until += 1; // a signed field
    assert_ne!(
        mutated.canonical_signed_bytes(),
        original,
        "canonical bytes must change when a signed field changes (content-sensitivity)"
    );
}
