//! PROPOSED license_heartbeat cross-language canonicalization golden vectors.
//!
//! PENDING Replit confirmation of the recipe — see
//! `/root/.bono-staging/SPEC-PROPOSAL-license-heartbeat-canonical-signing-20260601.md`.
//! This is the build-prerequisite Replit flagged ("pin the heartbeat recipe
//! before INC-7 wires verify"). It proves the Rust canonicalizer and the TS
//! generator (`tests/golden/gen-heartbeat-golden-vector.mjs`) agree byte-for-byte
//! on the PROPOSED recipe, and freezes it so a later drift is caught.
//!
//! OWNERSHIP (per Replit reply 2026-06-01): there is no `LicenseHeartbeat` schema
//! in `packages/contracts` yet — release.yaml Phase L §7 is "SPEC ONLY". The
//! canonical source of truth WILL be the Replit-authored `packages/contracts`
//! `LicenseHeartbeat` (YAML + zod + canonical serializer + parity gate), gated on
//! an AUTH-MEMO-1 rule #5 ratify packet + Captain sign-off (tier-auth / B9 key
//! surface). This signer MIRRORS that contract and is a test-vector source — it is
//! NOT the reference (same precedent as `ReleaseManifest` ← `release.ts`). A1
//! (`feature_opt_in` = boolean) + A2 (`machine_fingerprint` = composite sha256-hex
//! in the signed payload) are doctrinally CONSISTENT (capability-manifest
//! `FeatureOptInMatrix` all `z.boolean()`; threat_model Q-INSTALLER-32 / R-135) but
//! not yet schema-pinned. Post-ratify, the contract serializer emits the canonical
//! bytes and this test diffs against them.
//!
//! SCAFFOLD SCOPE (deliberately test-local): the `LicenseHeartbeat` type +
//! `canonical_signed_bytes` live HERE, not in `src/`. The live claim/refresh
//! verifier is INC-7 (credential pivot) and lands only under per-PR Captain
//! (human) auth. When it does, this type graduates to `src/heartbeat.rs` and
//! these tests switch to `use rc_installer::heartbeat::LicenseHeartbeat;` — the
//! fixture (canonical_bytes_hex + frozen anchor) is the language-agnostic
//! contract that pins whatever lands in src.
//!
//! Recipe (mirrors `src/manifest.rs` `canonical_signed_bytes`): compact JSON,
//! struct-DECLARATION field order, `signature` excluded, `feature_opt_in` keys
//! sorted (BTreeMap → sorted for free), `issued_at`/`valid_until` = Unix ms.
//!
//! Regenerate the fixture with:
//!   node crates/rc-installer/tests/golden/gen-heartbeat-golden-vector.mjs

use ed25519_dalek::{Signature, VerifyingKey};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

const GOLDEN: &str = include_str!("golden/license-heartbeat-golden.json");

/// Frozen spec anchor — NOT regenerated by the generator. The exact canonical
/// signed bytes for the production vector. If the canonicalization recipe drifts
/// (field order/format/sort), `canonical_signed_bytes` diverges from this even
/// after a fixture regenerate, so a silent recipe change fails here.
const EXPECTED_PRODUCTION_CANONICAL: &str = r#"{"tenant_id":"rp-hyd","machine_fingerprint":"f0e1d2c3b4a5968778695a4b3c2d1e0f00112233445566778899aabbccddeeff","issued_at":1748649600000,"valid_until":1748653200000,"signing_key_id":"rc-hb-test-001","license_class":"production","feature_opt_in":{"multiplayer":true,"telemetry":false}}"#;

/// Test-local mirror of the PROPOSED `license_heartbeat` (Q1). Graduates to
/// `src/heartbeat.rs` at INC-7. `signature` is carried for round-trips but
/// EXCLUDED from the signed bytes (see [`CanonicalHeartbeat`]).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct LicenseHeartbeat {
    tenant_id: String,
    machine_fingerprint: String,
    issued_at: u64,
    valid_until: u64,
    signing_key_id: String,
    license_class: String,
    /// Object with values; canonicalizes with SORTED keys (BTreeMap).
    feature_opt_in: BTreeMap<String, bool>,
    /// ed25519 signature, hex. EXCLUDED from `canonical_signed_bytes`.
    signature: String,
}

/// Borrowing view that serializes every field EXCEPT `signature`, in
/// declaration order — the bytes the ed25519 signature covers. (Same pattern as
/// `src/manifest.rs::CanonicalManifest`: not `#[serde(skip)]` which would break
/// deserialize round-trips, not `serde_json::Value` which would alphabetize.)
#[derive(Serialize)]
struct CanonicalHeartbeat<'a> {
    tenant_id: &'a str,
    machine_fingerprint: &'a str,
    issued_at: u64,
    valid_until: u64,
    signing_key_id: &'a str,
    license_class: &'a str,
    feature_opt_in: &'a BTreeMap<String, bool>,
}

impl LicenseHeartbeat {
    /// The exact bytes the ed25519 signature covers: all fields except
    /// `signature`, compact JSON, struct-declaration order. MUST stay
    /// byte-identical to the TS canonicalizer.
    fn canonical_signed_bytes(&self) -> Vec<u8> {
        let canonical = CanonicalHeartbeat {
            tenant_id: &self.tenant_id,
            machine_fingerprint: &self.machine_fingerprint,
            issued_at: self.issued_at,
            valid_until: self.valid_until,
            signing_key_id: &self.signing_key_id,
            license_class: &self.license_class,
            feature_opt_in: &self.feature_opt_in,
        };
        serde_json::to_vec(&canonical).expect("canonical serialize")
    }
}

fn fixture() -> serde_json::Value {
    serde_json::from_str(GOLDEN).expect("parse golden fixture")
}

fn heartbeat_of(v: &serde_json::Value) -> LicenseHeartbeat {
    serde_json::from_value(v["heartbeat"].clone()).expect("heartbeat deserializes")
}

/// Fail-closed ed25519 verify over `message` with a hex pubkey + hex signature.
/// Mirrors `src/signature_verifier.rs` Gate 4–5 (`verify_strict`).
fn verify(message: &[u8], signature_hex: &str, public_key_hex: &str) -> bool {
    let Ok(sig_bytes) = hex::decode(signature_hex) else { return false };
    let Ok(signature) = Signature::try_from(sig_bytes.as_slice()) else { return false };
    let Ok(pk_bytes) = hex::decode(public_key_hex) else { return false };
    let Ok(pk_arr) = <[u8; 32]>::try_from(pk_bytes.as_slice()) else { return false };
    let Ok(vk) = VerifyingKey::from_bytes(&pk_arr) else { return false };
    vk.verify_strict(message, &signature).is_ok()
}

/// Every vector: Rust canonical bytes are byte-identical to the TS canonicalizer
/// AND the TS ed25519 signature verifies. Covers production (non-empty
/// feature_opt_in) and trial (empty) — both license classes, both map shapes.
#[test]
fn all_vectors_byte_parity_and_verify() {
    let f = fixture();
    let vectors = f["vectors"].as_array().expect("vectors array");
    assert!(vectors.len() >= 2, "need >=2 vectors (production + trial)");
    let (mut saw_production, mut saw_trial) = (false, false);
    for v in vectors {
        let label = v["label"].as_str().unwrap_or("?");
        let hb = heartbeat_of(v);
        let expected_hex = v["canonical_bytes_hex"].as_str().unwrap();
        assert_eq!(
            hex::encode(hb.canonical_signed_bytes()),
            expected_hex,
            "[{label}] Rust canonical bytes diverged from the TS canonicalizer"
        );
        assert!(
            verify(&hb.canonical_signed_bytes(), &hb.signature, v["public_key_hex"].as_str().unwrap()),
            "[{label}] ed25519 verify_strict must accept the TS signature"
        );
        match hb.license_class.as_str() {
            "production" => saw_production = true,
            "trial" => saw_trial = true,
            other => panic!("[{label}] unexpected license_class {other}"),
        }
    }
    assert!(saw_production && saw_trial, "vectors must cover both production and trial");
}

/// Frozen spec anchor: the production canonical bytes equal the hardcoded
/// constant — independent of fixture regeneration (catches a silent recipe change).
#[test]
fn production_canonical_matches_frozen_spec_anchor() {
    let f = fixture();
    let v = f["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| heartbeat_of(v).license_class == "production")
        .expect("a production vector");
    assert_eq!(
        heartbeat_of(v).canonical_signed_bytes(),
        EXPECTED_PRODUCTION_CANONICAL.as_bytes(),
        "canonical_signed_bytes drifted from the frozen spec anchor — a canonicalization recipe change leaked through a fixture regenerate"
    );
}

/// Non-vacuity on the KEY axis: a valid-but-unrelated key must NOT verify.
#[test]
fn wrong_key_fails_verify() {
    let f = fixture();
    let v = &f["vectors"].as_array().unwrap()[0];
    let hb = heartbeat_of(v);
    let wrong = f["wrong_public_key_hex"].as_str().unwrap();
    assert!(
        !verify(&hb.canonical_signed_bytes(), &hb.signature, wrong),
        "a valid-but-unrelated key must fail verify"
    );
}

/// Non-vacuity on the PAYLOAD axis: mutating a signed field breaks verification.
#[test]
fn tampered_signed_field_fails_verify() {
    let f = fixture();
    let v = f["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| heartbeat_of(v).license_class == "production")
        .expect("a production vector");
    let mut hb = heartbeat_of(v);
    hb.valid_until += 1; // a signed field (extends the TTL)
    assert!(
        !verify(&hb.canonical_signed_bytes(), &hb.signature, v["public_key_hex"].as_str().unwrap()),
        "a tampered signed field must fail ed25519 verify_strict"
    );
}
