//! L1-5 — cross-language canonicalization golden vectors (before-real-key gate #6).
//!
//! The TS-side generator (`tests/golden/gen-golden-vector.mjs`) produces signed
//! ReleaseManifest vectors using the SAME recipe as the Rust trust core (compact
//! JSON, struct-declaration order, `signature` excluded). These tests prove the
//! two languages agree, across the production-relevant shapes:
//!   - byte-parity: `canonical_signed_bytes()` is byte-identical to the TS output,
//!   - verify: `verify_manifest` accepts the TS ed25519 signature,
//!   - for BOTH previous_release_id=null (first release) and Some (upgrade), and
//!     1 vs 2 artifacts,
//!   - non-vacuity on both axes: a wrong key and a tampered field each fail.
//!
//! A hardcoded spec anchor pins the first-release canonical bytes independent of
//! fixture regeneration (catches a silent canonicalization-recipe change).
//!
//! Regenerate the fixture with:
//!   node crates/rc-installer/tests/golden/gen-golden-vector.mjs

use rc_installer::error::VerifyError;
use rc_installer::manifest::ReleaseManifest;
use rc_installer::signature_verifier::verify_manifest;
use rc_installer::trusted_keys::{TrustedKey, TrustedKeySet};

const GOLDEN: &str = include_str!("golden/release-manifest-golden.json");

/// Frozen spec anchor — NOT regenerated by the generator. The exact canonical
/// signed bytes for the first-release (previous_release_id=null) vector. If
/// CanonicalManifest field order/format drifts, `canonical_signed_bytes` diverges
/// from this even after a fixture regenerate, so a silent recipe change fails here.
const EXPECTED_FIRST_RELEASE_CANONICAL: &str = r#"{"release_id":"rel-2026Q2-golden","release_class":"feature","release_ring":"general","artifacts":[{"artifact_id":"rc-agent-2026Q2-001","sha256":"bd77425d29ddbe042bc9343ed565ad6c958b17f60b443453585e7085ed20e82f","size_bytes":16,"target":"rc-agent"}],"installer_artifact":{"sha256":"917ff608ad6b12559ba50bf481b6e1530d04a0a656dd176ee9c651000a5bd2c4","size_bytes":21,"download_url":"https://console.racecontrol.in/install/bootstrapper","signing_key_id":"rc-golden-test-001"},"previous_release_id":null,"cut_at":1748649600000,"signing_key_id":"rc-golden-test-001"}"#;

fn fixture() -> serde_json::Value {
    serde_json::from_str(GOLDEN).expect("parse golden fixture")
}

fn manifest_of(v: &serde_json::Value) -> ReleaseManifest {
    serde_json::from_value(v["manifest"].clone()).expect("manifest deserializes")
}

fn trusted(kid: &str, pubkey_hex: &str) -> TrustedKeySet {
    TrustedKeySet {
        keys: vec![TrustedKey { kid: kid.into(), public_key: pubkey_hex.into(), status: "active".into() }],
    }
}

/// Every vector: Rust canonical bytes are byte-identical to the TS canonicalizer
/// AND the TS ed25519 signature verifies. Covers null + Some(previous_release_id)
/// and 1 + 2 artifacts — the production upgrade shape, not just first-release.
#[test]
fn all_vectors_byte_parity_and_verify() {
    let f = fixture();
    let vectors = f["vectors"].as_array().expect("vectors array");
    assert!(vectors.len() >= 2, "need >=2 vectors (null + Some prev)");
    let (mut saw_null, mut saw_some) = (false, false);
    for v in vectors {
        let label = v["label"].as_str().unwrap_or("?");
        let manifest = manifest_of(v);
        let expected_hex = v["canonical_bytes_hex"].as_str().unwrap();
        assert_eq!(
            hex::encode(manifest.canonical_signed_bytes().unwrap()),
            expected_hex,
            "[{label}] Rust canonical bytes diverged from the TS canonicalizer"
        );
        let t = trusted(v["kid"].as_str().unwrap(), v["public_key_hex"].as_str().unwrap());
        assert_eq!(verify_manifest(&manifest, &t), Ok(()), "[{label}] verify_manifest must accept the TS signature");
        if manifest.previous_release_id.is_none() {
            saw_null = true;
        } else {
            saw_some = true;
        }
    }
    assert!(saw_null && saw_some, "vectors must cover both previous_release_id=null and Some");
}

/// Frozen spec anchor: the first-release canonical bytes equal the hardcoded
/// constant — independent of fixture regeneration (catches a silent recipe change).
#[test]
fn first_release_canonical_matches_frozen_spec_anchor() {
    let f = fixture();
    let v = f["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| manifest_of(v).previous_release_id.is_none())
        .expect("a first-release (null prev) vector");
    assert_eq!(
        manifest_of(v).canonical_signed_bytes().unwrap(),
        EXPECTED_FIRST_RELEASE_CANONICAL.as_bytes(),
        "canonical_signed_bytes drifted from the frozen spec anchor — a canonicalization recipe change leaked through a fixture regenerate"
    );
}

/// Non-vacuity on the KEY axis: a valid-but-unrelated key must NOT verify an
/// otherwise-untouched manifest (proves the signature check, not just the payload).
#[test]
fn wrong_key_fails_verify() {
    let f = fixture();
    let v = &f["vectors"].as_array().unwrap()[0];
    let manifest = manifest_of(v);
    let wrong = trusted(v["kid"].as_str().unwrap(), f["wrong_public_key_hex"].as_str().unwrap());
    assert!(
        matches!(verify_manifest(&manifest, &wrong), Err(VerifyError::BadSignature)),
        "a valid-but-unrelated key must fail verify with BadSignature"
    );
}

/// Non-vacuity on the PAYLOAD axis: mutating a signed field breaks verification.
#[test]
fn tampered_signed_field_fails_verify() {
    let f = fixture();
    let v = &f["vectors"].as_array().unwrap()[0];
    let mut manifest = manifest_of(v);
    manifest.cut_at += 1; // a signed field
    let t = trusted(v["kid"].as_str().unwrap(), v["public_key_hex"].as_str().unwrap());
    assert!(
        matches!(verify_manifest(&manifest, &t), Err(VerifyError::BadSignature)),
        "a tampered signed field must fail ed25519 verify_strict with BadSignature"
    );
}
