//! MIRROR of the Captain-PINNED license_heartbeat recipe, verifying Replit's
//! CEREMONY-SIGNED golden vectors (B9 ceremony 2026-06-01, rule #5 ratified).
//!
//! CANONICAL HOME = `packages/contracts` (`license.yaml` + `src/license.ts`) —
//! Replit-owned, parity-gated source of truth. This test + the generator MIRROR it
//! and MUST NOT drift. (Same ownership precedent as `ReleaseManifest` ← `release.ts`.)
//!
//! CEREMONY: vectors signed by the ceremony TEST key `rc-hb-test-001`. The production
//! B9 key `lic-sign-2026-06-1` was generated + custodied by Replit (private half never
//! left their sandbox; bono holds NO private material) and is RESERVED for live INC-7
//! issuance — it did NOT sign these vectors (used here as the wrong-key non-vacuity).
//! Cross-implementation parity is proven cryptographically: Replit's ed25519 signatures
//! verify against the canonical bytes this mirror reconstructs (any 1-byte diff fails).
//!
//! Recipe (= `packages/contracts` `canonicalJson()`): compact JSON, declaration-order,
//! `signature` excluded, `feature_opt_in` OPEN Record<string,boolean> keys sorted
//! (BTreeMap), `issued_at`/`valid_until` Unix-ms. Envelope `SignedLicenseHeartbeat
//! { license_heartbeat, signature, next_refresh_after }`; only `license_heartbeat`
//! (the 7 fields) is signed.
//!
//! When INC-7 lands (per-PR Captain auth), this type graduates to `src/heartbeat.rs`
//! and the live claim/refresh path verifies against the production B9 public key.
//! Regenerate the fixture with:
//!   node crates/rc-installer/tests/golden/gen-heartbeat-golden-vector.mjs

use ed25519_dalek::{Signature, VerifyingKey};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

const GOLDEN: &str = include_str!("golden/license-heartbeat-golden.json");

/// Frozen spec anchors — NOT regenerated by the generator. The exact canonical signed
/// bytes for the pinned production / trial vectors (Replit's ceremony fingerprint
/// `0123…×4`). If the recipe drifts, `canonical_signed_bytes` diverges from these even
/// after a regenerate. Production = 284 bytes, trial = 243.
const EXPECTED_PRODUCTION_CANONICAL: &str = r#"{"tenant_id":"rp-hyd","machine_fingerprint":"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef","issued_at":1748649600000,"valid_until":1748653200000,"signing_key_id":"rc-hb-test-001","license_class":"production","feature_opt_in":{"multiplayer":true,"telemetry":false}}"#;
const EXPECTED_TRIAL_CANONICAL: &str = r#"{"tenant_id":"rp-hyd","machine_fingerprint":"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef","issued_at":1748649600000,"valid_until":1748653200000,"signing_key_id":"rc-hb-test-001","license_class":"trial","feature_opt_in":{}}"#;

/// Test-local mirror of the PINNED `license_heartbeat` SIGNED PAYLOAD (7 signed fields;
/// `signature` is a 200-body sibling, kept beside the payload in the fixture).
/// Graduates to `src/heartbeat.rs` at INC-7.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct LicenseHeartbeat {
    tenant_id: String,
    machine_fingerprint: String,
    issued_at: u64,
    valid_until: u64,
    signing_key_id: String,
    license_class: String,
    /// OPEN Record<string,boolean>; canonicalizes with SORTED keys (BTreeMap).
    feature_opt_in: BTreeMap<String, bool>,
}

/// Borrowing view that serializes the signed payload in declaration order — the bytes
/// the ed25519 signature covers. Same pattern as `src/manifest.rs::CanonicalManifest`.
#[derive(Serialize)]
struct CanonicalHeartbeat<'a> {
    tenant_id: &'a str,
    machine_fingerprint: &'a str,
    issued_at: u64,
    valid_until: u64,
    signing_key_id: &'a str,
    license_class: &'a str,
    feature_opt_in: &'a BTreeMap<String, bool>,
}

impl LicenseHeartbeat {
    fn canonical_signed_bytes(&self) -> Vec<u8> {
        let canonical = CanonicalHeartbeat {
            tenant_id: &self.tenant_id,
            machine_fingerprint: &self.machine_fingerprint,
            issued_at: self.issued_at,
            valid_until: self.valid_until,
            signing_key_id: &self.signing_key_id,
            license_class: &self.license_class,
            feature_opt_in: &self.feature_opt_in,
        };
        serde_json::to_vec(&canonical).expect("canonical serialize")
    }
}

fn fixture() -> serde_json::Value {
    serde_json::from_str(GOLDEN).expect("parse golden fixture")
}

fn heartbeat_of(v: &serde_json::Value) -> LicenseHeartbeat {
    serde_json::from_value(v["license_heartbeat"].clone()).expect("license_heartbeat deserializes")
}

/// Fail-closed ed25519 verify over `message` with a hex pubkey + hex signature.
/// Mirrors `src/signature_verifier.rs` Gate 4–5 (`verify_strict`).
fn verify(message: &[u8], signature_hex: &str, public_key_hex: &str) -> bool {
    let Ok(sig_bytes) = hex::decode(signature_hex) else { return false };
    let Ok(signature) = Signature::try_from(sig_bytes.as_slice()) else { return false };
    let Ok(pk_bytes) = hex::decode(public_key_hex) else { return false };
    let Ok(pk_arr) = <[u8; 32]>::try_from(pk_bytes.as_slice()) else { return false };
    let Ok(vk) = VerifyingKey::from_bytes(&pk_arr) else { return false };
    vk.verify_strict(message, &signature).is_ok()
}

fn vector_signing_pubkey(f: &serde_json::Value) -> String {
    f["vector_signing_public_key_hex"].as_str().unwrap().to_string()
}

/// Byte-parity + length for every vector (production + trial; both license classes).
#[test]
fn all_vectors_byte_parity_and_length() {
    let f = fixture();
    let vectors = f["vectors"].as_array().expect("vectors array");
    assert!(vectors.len() >= 2, "need >=2 vectors (production + trial)");
    let (mut saw_production, mut saw_trial) = (false, false);
    for v in vectors {
        let label = v["label"].as_str().unwrap_or("?");
        let bytes = heartbeat_of(v).canonical_signed_bytes();
        assert_eq!(hex::encode(&bytes), v["canonical_bytes_hex"].as_str().unwrap(), "[{label}] canonical bytes diverged from the TS canonicalizer");
        assert_eq!(bytes.len() as u64, v["canonical_byte_len"].as_u64().unwrap(), "[{label}] canonical byte length diverged");
        match heartbeat_of(v).license_class.as_str() {
            "production" => saw_production = true,
            "trial" => saw_trial = true,
            other => panic!("[{label}] unexpected license_class {other}"),
        }
    }
    assert!(saw_production && saw_trial, "vectors must cover both production and trial");
}

/// Real-key signature parity: Replit's ceremony signature (rc-hb-test-001) verifies
/// against the canonical bytes this mirror reconstructs — the cross-implementation
/// byte-for-byte proof (any 1-byte diff would fail ed25519 verify_strict).
#[test]
fn all_vectors_signature_verifies() {
    let f = fixture();
    let pubkey = vector_signing_pubkey(&f);
    for v in f["vectors"].as_array().unwrap() {
        let label = v["label"].as_str().unwrap_or("?");
        let bytes = heartbeat_of(v).canonical_signed_bytes();
        assert!(
            verify(&bytes, v["signature_hex"].as_str().unwrap(), &pubkey),
            "[{label}] ceremony signature must verify against the reconstructed canonical bytes"
        );
    }
}

/// Frozen anchor: production canonical bytes == constant AND 284 bytes.
#[test]
fn production_canonical_matches_frozen_spec_anchor() {
    let f = fixture();
    let v = f["vectors"].as_array().unwrap().iter().find(|v| heartbeat_of(v).license_class == "production").expect("a production vector");
    let bytes = heartbeat_of(v).canonical_signed_bytes();
    assert_eq!(bytes, EXPECTED_PRODUCTION_CANONICAL.as_bytes(), "production canonical drifted from the frozen spec anchor");
    assert_eq!(bytes.len(), 284, "production canonical must be 284 bytes");
}

/// Frozen anchor: trial canonical bytes == constant AND 243 bytes (same kid as production).
#[test]
fn trial_canonical_matches_frozen_spec_anchor() {
    let f = fixture();
    let v = f["vectors"].as_array().unwrap().iter().find(|v| heartbeat_of(v).license_class == "trial").expect("a trial vector");
    let bytes = heartbeat_of(v).canonical_signed_bytes();
    assert_eq!(bytes, EXPECTED_TRIAL_CANONICAL.as_bytes(), "trial canonical drifted from the frozen spec anchor");
    assert_eq!(bytes.len(), 243, "trial canonical must be 243 bytes");
}

/// Non-vacuity (KEY axis): the RESERVED production key (lic-sign-2026-06-1) must NOT
/// verify the test vectors — proves the verify checks the actual signer AND that the
/// production key did not sign these test payloads.
#[test]
fn reserved_production_key_does_not_verify_test_vectors() {
    let f = fixture();
    let reserved = f["production_reserved_public_key_hex"].as_str().unwrap();
    let v = &f["vectors"].as_array().unwrap()[0];
    let bytes = heartbeat_of(v).canonical_signed_bytes();
    assert!(
        !verify(&bytes, v["signature_hex"].as_str().unwrap(), reserved),
        "the reserved production key must NOT verify a test-key-signed vector"
    );
}

/// Non-vacuity (PAYLOAD axis): mutating a signed field breaks the signature.
#[test]
fn tampered_signed_field_fails_verify() {
    let f = fixture();
    let pubkey = vector_signing_pubkey(&f);
    let v = f["vectors"].as_array().unwrap().iter().find(|v| heartbeat_of(v).license_class == "production").unwrap();
    let mut hb = heartbeat_of(v);
    hb.valid_until += 1; // a signed field
    assert!(
        !verify(&hb.canonical_signed_bytes(), v["signature_hex"].as_str().unwrap(), &pubkey),
        "a tampered signed field must fail ed25519 verify_strict"
    );
}
