//! TLS certificate generation and RustlsConfig loader.
//!
//! Provides two paths:
//!
//! 1. **Legacy one-way TLS** (`load_or_generate_rustls_config`) -- generates a self-signed
//!    certificate for the server IP and returns a `RustlsConfig` for HTTPS. Used by the
//!    existing `tls_port` config option. No client cert verification.
//!
//! 2. **Venue CA mTLS** (`load_mtls_config`) -- loads CA-signed server cert from disk
//!    (generated by `scripts/generate-venue-ca.sh`). Optionally requires clients to
//!    present a venue CA-signed cert (`require_client_cert = true`). Tailscale connections
//!    (100.64.0.0/10) are exempted -- they bypass the client cert requirement.
//!    Used by Phase 305 `[server.tls]` config section.

use axum_server::tls_rustls::RustlsConfig;
use rcgen::{generate_simple_self_signed, CertifiedKey};
use std::path::Path;

use crate::config::MtlsConfig;

const DEFAULT_CERT_DIR: &str = "C:\\RacingPoint\\tls";
const CERT_FILENAME: &str = "cert.pem";
const KEY_FILENAME: &str = "key.pem";

/// Load existing PEM files or generate a self-signed cert for the server IP.
///
/// If `cert_path` or `key_path` are None, defaults to `C:\RacingPoint\tls\{cert,key}.pem`.
/// If the PEM files do not exist on disk, generates a new self-signed certificate
/// with IP SAN for `server_ip` and DNS SAN for `localhost`.
pub async fn load_or_generate_rustls_config(
    server_ip: &str,
    cert_path: Option<&str>,
    key_path: Option<&str>,
) -> anyhow::Result<RustlsConfig> {
    let cert_file = cert_path
        .map(|p| p.to_string())
        .unwrap_or_else(|| format!("{}\\{}", DEFAULT_CERT_DIR, CERT_FILENAME));
    let key_file = key_path
        .map(|p| p.to_string())
        .unwrap_or_else(|| format!("{}\\{}", DEFAULT_CERT_DIR, KEY_FILENAME));

    if !Path::new(&cert_file).exists() || !Path::new(&key_file).exists() {
        tracing::info!("TLS certificates not found, generating self-signed for {}", server_ip);
        generate_and_save(server_ip, &cert_file, &key_file)?;
    }

    let config = RustlsConfig::from_pem_file(&cert_file, &key_file).await?;
    tracing::info!("TLS configured from {} and {}", cert_file, key_file);
    Ok(config)
}

/// Generate a self-signed X.509 certificate with IP SAN and localhost DNS SAN,
/// then write cert.pem and key.pem to the specified paths.
fn generate_and_save(server_ip: &str, cert_path: &str, key_path: &str) -> anyhow::Result<()> {
    let subject_alt_names = vec![server_ip.to_string(), "localhost".to_string()];
    let CertifiedKey { cert, signing_key } = generate_simple_self_signed(subject_alt_names)?;

    if let Some(parent) = Path::new(cert_path).parent() {
        std::fs::create_dir_all(parent)?;
    }
    if let Some(parent) = Path::new(key_path).parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(cert_path, cert.pem())?;
    std::fs::write(key_path, signing_key.serialize_pem())?;
    tracing::info!("Self-signed TLS certificate generated for IP {}", server_ip);
    Ok(())
}

/// Load venue CA mTLS config from disk (certs generated by `scripts/generate-venue-ca.sh`).
///
/// When `require_client_cert = false` (default), returns a `RustlsConfig` using the
/// server cert -- no client cert verification (one-way TLS).
///
/// When `require_client_cert = true`, builds a `RustlsConfig` with a
/// `WebPkiClientVerifier` that validates client certs against the venue CA (full mTLS).
///
/// Returns an error if any cert/key file is missing or cannot be parsed.
pub async fn load_mtls_config(tls: &MtlsConfig) -> anyhow::Result<RustlsConfig> {
    for (label, path) in [
        ("CA cert", &tls.ca_cert_path),
        ("server cert", &tls.server_cert_path),
        ("server key", &tls.server_key_path),
    ] {
        if !Path::new(path).exists() {
            anyhow::bail!(
                "mTLS {label} not found at '{path}'. \
                 Run 'bash scripts/generate-venue-ca.sh' to generate certificates."
            );
        }
    }

    if tls.require_client_cert {
        build_mtls_config_with_client_verify(tls).await
    } else {
        let config = RustlsConfig::from_pem_file(&tls.server_cert_path, &tls.server_key_path).await?;
        tracing::info!(
            "Venue CA TLS (one-way) configured -- server cert: {}, client certs: not required",
            tls.server_cert_path
        );
        Ok(config)
    }
}

/// Build a `RustlsConfig` that requires clients to present a venue CA-signed certificate.
async fn build_mtls_config_with_client_verify(tls: &MtlsConfig) -> anyhow::Result<RustlsConfig> {
    use rustls::RootCertStore;
    use rustls::pki_types::{CertificateDer, PrivateKeyDer, pem::PemObject};
    use rustls::server::WebPkiClientVerifier;
    use std::sync::Arc;

    let ca_pem = std::fs::read_to_string(&tls.ca_cert_path)
        .map_err(|e| anyhow::anyhow!("Failed to read CA cert '{}': {}", tls.ca_cert_path, e))?;

    let mut root_store = RootCertStore::empty();
    let ca_certs: Vec<CertificateDer<'static>> =
        CertificateDer::pem_slice_iter(ca_pem.as_bytes())
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| anyhow::anyhow!("Failed to parse CA cert PEM: {}", e))?;

    for cert in ca_certs {
        root_store
            .add(cert)
            .map_err(|e| anyhow::anyhow!("Failed to add CA cert to trust store: {}", e))?;
    }

    let server_cert_pem = std::fs::read_to_string(&tls.server_cert_path)
        .map_err(|e| anyhow::anyhow!("Failed to read server cert '{}': {}", tls.server_cert_path, e))?;
    let server_certs: Vec<CertificateDer<'static>> =
        CertificateDer::pem_slice_iter(server_cert_pem.as_bytes())
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| anyhow::anyhow!("Failed to parse server cert PEM: {}", e))?;

    let server_key_pem = std::fs::read_to_string(&tls.server_key_path)
        .map_err(|e| anyhow::anyhow!("Failed to read server key '{}': {}", tls.server_key_path, e))?;
    let server_key = PrivateKeyDer::from_pem_slice(server_key_pem.as_bytes())
        .map_err(|e| anyhow::anyhow!("Failed to parse server key PEM: {}", e))?;

    let client_verifier = WebPkiClientVerifier::builder(Arc::new(root_store))
        .build()
        .map_err(|e| anyhow::anyhow!("Failed to build client verifier: {}", e))?;

    let rustls_config = rustls::ServerConfig::builder()
        .with_client_cert_verifier(client_verifier)
        .with_single_cert(server_certs, server_key)
        .map_err(|e| anyhow::anyhow!("Failed to build rustls ServerConfig: {}", e))?;

    tracing::info!(
        "Venue CA mTLS (mutual) configured -- CA: {}, server cert: {}, client certs: REQUIRED",
        tls.ca_cert_path, tls.server_cert_path
    );

    Ok(RustlsConfig::from_config(Arc::new(rustls_config)))
}

/// Returns true if the IP string is in the Tailscale range 100.64.0.0/10.
///
/// Tailscale allocates from RFC 6598 shared address space: 100.64.0.0-100.127.255.255.
/// These connections are end-to-end encrypted by WireGuard -- mTLS client cert
/// requirements are bypassed for them when `tailscale_bypass = true`.
pub fn is_tailscale_ip(ip: &str) -> bool {
    let parts: Vec<&str> = ip.split('.').collect();
    if parts.len() < 2 {
        return false;
    }
    let first: u8 = parts[0].parse().unwrap_or(0);
    let second: u8 = parts[1].parse().unwrap_or(0);
    first == 100 && second >= 64 && second <= 127
}

/// Returns true if a `SocketAddr`'s IP is in the Tailscale range.
pub fn socket_addr_is_tailscale(addr: &std::net::SocketAddr) -> bool {
    is_tailscale_ip(&addr.ip().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn test_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir()
            .join("racecontrol_tls_tests")
            .join(name)
            .join(format!("{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("create test dir");
        dir
    }

    #[test]
    fn generate_and_save_creates_pem_files() {
        let dir = test_dir("pem_files");
        let cert_path = dir.join("cert.pem");
        let key_path = dir.join("key.pem");

        generate_and_save(
            "192.168.31.23",
            cert_path.to_str().expect("path"),
            key_path.to_str().expect("path"),
        )
        .expect("generate_and_save should succeed");

        assert!(cert_path.exists(), "cert.pem must exist");
        assert!(key_path.exists(), "key.pem must exist");

        let cert_content = std::fs::read_to_string(&cert_path).expect("read cert");
        let key_content = std::fs::read_to_string(&key_path).expect("read key");

        assert!(!cert_content.is_empty());
        assert!(!key_content.is_empty());
        assert!(cert_content.contains("-----BEGIN CERTIFICATE-----"));
        assert!(cert_content.contains("-----END CERTIFICATE-----"));
        assert!(key_content.contains("-----BEGIN PRIVATE KEY-----"));
        assert!(key_content.contains("-----END PRIVATE KEY-----"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn generate_and_save_cert_has_ip_san() {
        let dir = test_dir("ip_san");
        let cert_path = dir.join("cert.pem");
        let key_path = dir.join("key.pem");

        generate_and_save(
            "192.168.31.23",
            cert_path.to_str().expect("path"),
            key_path.to_str().expect("path"),
        )
        .expect("generate_and_save should succeed");

        let cert_pem = std::fs::read_to_string(&cert_path).expect("read cert");
        assert!(cert_pem.len() > 200);

        let cert_der = pem_to_der(&cert_pem);
        assert!(!cert_der.is_empty());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn load_or_generate_creates_missing_files() {
        let dir = test_dir("load_create");
        let cert_path = dir.join("cert.pem");
        let key_path = dir.join("key.pem");

        assert!(!cert_path.exists());
        assert!(!key_path.exists());

        let result = load_or_generate_rustls_config(
            "192.168.31.23",
            Some(cert_path.to_str().expect("path")),
            Some(key_path.to_str().expect("path")),
        )
        .await;

        assert!(result.is_ok(), "should succeed: {:?}", result.err());
        assert!(cert_path.exists());
        assert!(key_path.exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn load_or_generate_uses_existing_files() {
        let dir = test_dir("load_existing");
        let cert_path = dir.join("cert.pem");
        let key_path = dir.join("key.pem");

        generate_and_save(
            "192.168.31.23",
            cert_path.to_str().expect("path"),
            key_path.to_str().expect("path"),
        )
        .expect("pre-generate");

        let cert_modified = std::fs::metadata(&cert_path)
            .expect("cert metadata")
            .modified()
            .expect("modified time");
        let key_modified = std::fs::metadata(&key_path)
            .expect("key metadata")
            .modified()
            .expect("modified time");

        std::thread::sleep(std::time::Duration::from_millis(100));

        let result = load_or_generate_rustls_config(
            "192.168.31.23",
            Some(cert_path.to_str().expect("path")),
            Some(key_path.to_str().expect("path")),
        )
        .await;

        assert!(result.is_ok());

        let cert_modified_after = std::fs::metadata(&cert_path)
            .expect("cert metadata")
            .modified()
            .expect("modified time");
        let key_modified_after = std::fs::metadata(&key_path)
            .expect("key metadata")
            .modified()
            .expect("modified time");

        assert_eq!(cert_modified, cert_modified_after, "cert.pem should not be regenerated");
        assert_eq!(key_modified, key_modified_after, "key.pem should not be regenerated");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn tailscale_ip_true_cases() {
        assert!(is_tailscale_ip("100.92.122.89"),   "pod 1");
        assert!(is_tailscale_ip("100.105.93.108"),  "pod 2");
        assert!(is_tailscale_ip("100.69.231.26"),   "pod 3");
        assert!(is_tailscale_ip("100.75.45.10"),    "pod 4");
        assert!(is_tailscale_ip("100.110.133.87"),  "pod 5");
        assert!(is_tailscale_ip("100.127.149.17"),  "pod 6");
        assert!(is_tailscale_ip("100.82.196.28"),   "pod 7");
        assert!(is_tailscale_ip("100.98.67.67"),    "pod 8");
        assert!(is_tailscale_ip("100.125.108.37"),  "server");
        assert!(is_tailscale_ip("100.95.211.1"),    "POS");
        assert!(is_tailscale_ip("100.70.177.44"),   "Bono VPS");
        assert!(is_tailscale_ip("100.64.0.1"),      "lower boundary");
        assert!(is_tailscale_ip("100.127.255.254"), "upper boundary");
    }

    #[test]
    fn tailscale_ip_false_cases() {
        assert!(!is_tailscale_ip("192.168.31.89"),   "pod 1 LAN");
        assert!(!is_tailscale_ip("192.168.31.23"),   "server LAN");
        assert!(!is_tailscale_ip("192.168.31.20"),   "POS LAN");
        assert!(!is_tailscale_ip("127.0.0.1"),       "localhost");
        assert!(!is_tailscale_ip("10.0.0.1"),        "private 10.x");
        assert!(!is_tailscale_ip("172.16.0.1"),      "private 172.x");
        assert!(!is_tailscale_ip("100.63.255.255"),  "just below range");
        assert!(!is_tailscale_ip("100.128.0.1"),     "just above range");
        assert!(!is_tailscale_ip(""),                "empty");
        assert!(!is_tailscale_ip("not-an-ip"),       "non-IP");
    }

    #[test]
    fn tailscale_socket_addr_detection() {
        use std::net::{IpAddr, Ipv4Addr, SocketAddr};
        let ts_addr  = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(100, 92, 122, 89)), 8090);
        let lan_addr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(192, 168, 31, 89)), 8090);
        assert!( socket_addr_is_tailscale(&ts_addr));
        assert!(!socket_addr_is_tailscale(&lan_addr));
    }

    #[test]
    fn mtls_config_defaults_are_safe() {
        let cfg = MtlsConfig::default();
        assert!(!cfg.enabled,             "disabled by default");
        assert!(cfg.tailscale_bypass,     "tailscale bypass on by default");
        assert!(!cfg.require_client_cert, "client cert off by default");
    }

    #[tokio::test]
    async fn load_mtls_config_missing_files_returns_error() {
        let cfg = MtlsConfig {
            enabled: true,
            ca_cert_path: "/nonexistent/ca.pem".to_string(),
            server_cert_path: "/nonexistent/server.pem".to_string(),
            server_key_path: "/nonexistent/server-key.pem".to_string(),
            require_client_cert: false,
            tailscale_bypass: true,
        };
        let result = load_mtls_config(&cfg).await;
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("not found") || msg.contains("CA cert") || msg.contains("server cert"),
            "error should mention missing cert: {}",
            msg
        );
    }

    fn pem_to_der(pem: &str) -> Vec<u8> {
        let b64: String = pem
            .lines()
            .filter(|l| !l.starts_with("-----"))
            .collect::<Vec<_>>()
            .join("");
        base64::Engine::decode(&base64::engine::general_purpose::STANDARD, &b64)
            .unwrap_or_default()
    }
}
