#!/usr/bin/env node
// Rebuilds graphify-out/communities/index.html from the current graph.json
// (community sizes may have shifted after repair). Non-destructive: overwrites index only.

import fs from 'fs';
import path from 'path';

const outDir = process.argv[2] || 'graphify-out';
const graphPath = path.join(outDir, 'graph.json');
const indexPath = path.join(outDir, 'communities', 'index.html');

if (!fs.existsSync(graphPath)) {
  console.error(`ERROR: ${graphPath} missing`);
  process.exit(1);
}

const g = JSON.parse(fs.readFileSync(graphPath, 'utf8'));
const commCounts = new Map();
for (const n of g.nodes) commCounts.set(n.community, (commCounts.get(n.community)||0)+1);
const commEdges = new Map();
for (const e of g.links) {
  const sC = g.nodes.find(n => n.id === e.source)?.community;
  const tC = g.nodes.find(n => n.id === e.target)?.community;
  if (sC === tC && sC !== undefined) {
    commEdges.set(sC, (commEdges.get(sC)||0)+1);
  }
}

const comms = [...commCounts.entries()]
  .filter(([cid, n]) => n >= 5)  // only render communities with HTML files (graphify's default threshold)
  .sort((a,b)=>b[1]-a[1]);

let html = `<!doctype html>
<html><head><meta charset="utf-8"><title>Graphify subgraph index</title>
<style>
  body { font-family: -apple-system, Segoe UI, sans-serif; background: #0f0f1a; color: #e0e0e0; padding: 24px; }
  h1 { font-size: 18px; margin-bottom: 4px; }
  .meta { color: #999; font-size: 13px; margin-bottom: 18px; }
  table { border-collapse: collapse; font-size: 13px; }
  th, td { padding: 6px 12px; border-bottom: 1px solid #2a2a4e; text-align: left; }
  th { color: #aaa; text-transform: uppercase; font-size: 11px; letter-spacing: 0.05em; }
  a { color: #4E79A7; text-decoration: none; }
  a:hover { text-decoration: underline; }
  .gen { color: #666; font-size: 11px; margin-top: 20px; }
</style></head><body>
<h1>Graphify subgraph index</h1>
<div class="meta">
  ${comms.length} communities &mdash; ${g.nodes.length} nodes &mdash; ${g.links.length} edges
</div>
<table>
  <thead><tr><th>Community</th><th>Nodes</th><th>Internal edges</th><th>HTML</th></tr></thead>
  <tbody>`;
for (const [cid, n] of comms) {
  const e = commEdges.get(cid) || 0;
  const fname = `community_${cid}.html`;
  const exists = fs.existsSync(path.join(outDir, 'communities', fname));
  html += `
  <tr><td>${cid}</td><td>${n}</td><td>${e}</td><td>${exists ? `<a href="${fname}">${fname}</a>` : '<em>(no html)</em>'}</td></tr>`;
}
html += `
  </tbody>
</table>
<div class="gen">Regenerated by scripts/graphify-post/rebuild-index.mjs at ${new Date().toISOString()}</div>
</body></html>`;

fs.writeFileSync(indexPath, html);
console.log(`Wrote ${indexPath} (${comms.length} communities listed)`);
