#!/usr/bin/env bash
# security-env-template.sh — M13-SEC: Generate .env files for all services
#
# Creates template .env files with all required secrets as env vars.
# Prevents API keys from appearing in process listings (ps aux).
#
# Usage: bash scripts/security-env-template.sh > /path/to/.env.secrets

cat << 'TEMPLATE'
# Racing Point Secrets — DO NOT COMMIT TO GIT
# Generated by scripts/security-env-template.sh
# Load via: set -a; source .env.secrets; set +a

# ─── Server (racecontrol) ─────────────────────────────────────────────
RC_JWT_SECRET=
RC_ADMIN_PIN_HASH=
RC_TERMINAL_SECRET=
RC_EVOLUTION_API_KEY=
RC_EVOLUTION_URL=http://srv1422716.hstgr.cloud:53622
RC_RELAY_SECRET=
RC_SENTRY_SERVICE_KEY=

# ─── Comms-link ───────────────────────────────────────────────────────
COMMS_PSK=
COMMS_URL=ws://srv1422716.hstgr.cloud:8765

# ─── rc-sentry-ai ────────────────────────────────────────────────────
NVR_USERNAME=
NVR_PASSWORD=
SENTRY_AI_SERVICE_KEY=

# ─── OpenRouter (MMA audits) ─────────────────────────────────────────
OPENROUTER_KEY=

# ─── Google OAuth (marketing + MCP services) ──────────────────────────
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REFRESH_TOKEN=

# ─── Higgsfield (marketing videos) ───────────────────────────────────
HF_CREDENTIALS=
TEMPLATE

echo ""
echo "# Instructions:"
echo "# 1. Fill in all values above"
echo "# 2. Save as ~/.env.secrets (outside any git repo)"
echo "# 3. Add to shell profile: source ~/.env.secrets"
echo "# 4. Never pass secrets via command line args (visible in ps)"
echo "# 5. Never commit this file to git"
