//! Deploy executor: orchestrates rc-agent binary deployment to pods.
//!
//! The deploy lifecycle for a single pod:
//!   1. Validate binary URL is reachable (HEAD request)
//!   2. Kill rc-agent.exe on pod (taskkill /F /IM rc-agent.exe)
//!   3. Wait for process to exit (poll tasklist every 2s, up to 10s)
//!   4. Delete old binary (del /F C:\RacingPoint\rc-agent.exe)
//!   5. Download new binary (curl -s -f -o ... <url>)
//!   6. Verify binary size >= 5MB threshold
//!   7. Write config from template (via pod-agent /write)
//!   8. Start new rc-agent.exe (cd /d C:\RacingPoint && start /b rc-agent.exe)
//!   9. Verify health: process alive + WebSocket connected + lock screen responsive
//!
//! Each step updates DeployState in AppState and broadcasts DashboardEvent::DeployProgress.
//! On failure at any step, state is set to Failed and an email alert is sent.

use std::sync::Arc;
use std::time::Duration;

use chrono::Utc;

use crate::activity_log::log_pod_activity;
use crate::state::AppState;
use rc_common::protocol::DashboardEvent;
use rc_common::types::DeployState;

const POD_AGENT_PORT: u16 = 8090;
const MIN_BINARY_SIZE: u64 = 5_000_000; // 5MB minimum for a valid rc-agent.exe
const PROCESS_KILL_TIMEOUT_SECS: u64 = 10;
const PROCESS_POLL_INTERVAL_SECS: u64 = 2;
const VERIFY_DELAYS: &[u64] = &[5, 15, 30, 60];

/// Validate that a binary size meets the minimum threshold.
/// Returns Ok(()) if valid, Err with descriptive message if too small.
pub fn validate_binary_size(size_bytes: u64) -> Result<(), String> {
    if size_bytes < MIN_BINARY_SIZE {
        Err(format!(
            "Binary too small: {} bytes (minimum {} bytes / {}MB). \
             Possible corrupted download or HTML error page.",
            size_bytes, MIN_BINARY_SIZE, MIN_BINARY_SIZE / 1_000_000
        ))
    } else {
        Ok(())
    }
}

/// Parse the file size from Windows `dir` command output.
/// Example input line: "03/13/2026  10:30 AM        15,234,567 rc-agent.exe"
/// Returns the size in bytes, or None if parsing fails.
pub fn parse_file_size_from_dir(dir_output: &str) -> Option<u64> {
    for line in dir_output.lines() {
        if line.contains("rc-agent.exe")
            && !line.contains("File Not Found")
            && !line.contains("DIR")
        {
            // Split on whitespace, find the field before "rc-agent.exe"
            let parts: Vec<&str> = line.split_whitespace().collect();
            for (i, part) in parts.iter().enumerate() {
                if part.contains("rc-agent") && i > 0 {
                    // The field before the filename is the size (may have commas)
                    let size_str = parts[i - 1].replace(',', "");
                    return size_str.parse::<u64>().ok();
                }
            }
        }
    }
    None
}

/// Human-readable label for a deploy state (used in progress messages and logs).
pub fn deploy_step_label(state: &DeployState) -> String {
    match state {
        DeployState::Idle => "Idle".to_string(),
        DeployState::Killing => "Killing old rc-agent process".to_string(),
        DeployState::WaitingDead => "Waiting for old process to exit".to_string(),
        DeployState::Downloading { progress_pct } => {
            format!("Downloading new binary ({}%)", progress_pct)
        }
        DeployState::SizeCheck => "Verifying binary size".to_string(),
        DeployState::Starting => "Starting new rc-agent process".to_string(),
        DeployState::VerifyingHealth => {
            "Verifying pod health (process + WS + lock screen)".to_string()
        }
        DeployState::Complete => "Deploy completed successfully".to_string(),
        DeployState::Failed { reason } => format!("Deploy failed: {}", reason),
        DeployState::WaitingSession => "Waiting for active billing session to end".to_string(),
    }
}

/// Generate pod config content from a hardcoded template.
/// Mirrors the template at deploy-staging/rc-agent.template.toml.
pub fn generate_pod_config(pod_number: u32) -> String {
    let pod_name = format!("Pod {:02}", pod_number);
    format!(
        r#"# rc-agent Configuration (generated by deploy executor)
# Pod {pod_number} — {pod_name}

[pod]
number = {pod_number}
name = "{pod_name}"
sim = "assetto_corsa"
sim_ip = "127.0.0.1"
sim_port = 9996

[core]
url = "ws://192.168.31.23:8080/ws/agent"

[games.assetto_corsa]
steam_app_id = 244210
use_steam = true

[games.f1_25]
steam_app_id = 2488620
use_steam = true

[games.le_mans_ultimate]
steam_app_id = 1564310
use_steam = true

[games.forza]
steam_app_id = 2440510
use_steam = true

[games.iracing]
exe_path = "C:\\Program Files (x86)\\iRacing\\iRacingSim64DX11.exe"
use_steam = false

[ai_debugger]
enabled = true
ollama_url = "http://192.168.31.27:11434"
ollama_model = "qwen2.5-coder:14b"
"#,
        pod_number = pod_number,
        pod_name = pod_name
    )
}

/// Update deploy state for a pod, broadcast progress to dashboard, and log.
async fn set_deploy_state(state: &Arc<AppState>, pod_id: &str, deploy_state: DeployState) {
    let message = deploy_step_label(&deploy_state);
    let timestamp = Utc::now().to_rfc3339();

    // Update AppState
    {
        let mut deploy_states = state.pod_deploy_states.write().await;
        deploy_states.insert(pod_id.to_string(), deploy_state.clone());
    }

    // Broadcast to dashboard
    let _ = state.dashboard_tx.send(DashboardEvent::DeployProgress {
        pod_id: pod_id.to_string(),
        state: deploy_state.clone(),
        message: message.clone(),
        timestamp,
    });

    // Log significant state changes
    match &deploy_state {
        DeployState::Idle => {}
        _ => {
            tracing::info!("Deploy [{}]: {}", pod_id, message);
        }
    }
}

/// Execute a command on a pod via pod-agent POST /exec.
/// Returns (success, stdout, stderr).
async fn exec_on_pod(
    state: &Arc<AppState>,
    pod_ip: &str,
    cmd: &str,
    timeout_ms: u64,
) -> Result<(bool, String, String), String> {
    let url = format!("http://{}:{}/exec", pod_ip, POD_AGENT_PORT);
    let result = state
        .http_client
        .post(&url)
        .json(&serde_json::json!({
            "cmd": cmd,
            "timeout_ms": timeout_ms
        }))
        .timeout(Duration::from_millis(timeout_ms + 5000))
        .send()
        .await;

    match result {
        Ok(resp) => {
            let status_ok = resp.status().is_success();
            match resp.json::<serde_json::Value>().await {
                Ok(body) => {
                    let success = body["success"].as_bool().unwrap_or(status_ok);
                    let stdout = body["stdout"].as_str().unwrap_or("").to_string();
                    let stderr = body["stderr"].as_str().unwrap_or("").to_string();
                    Ok((success, stdout, stderr))
                }
                Err(e) => Err(format!("Failed to parse exec response: {}", e)),
            }
        }
        Err(e) => Err(format!("Failed to reach pod-agent: {}", e)),
    }
}

/// Check if rc-agent.exe is running on the pod.
async fn is_process_alive(state: &Arc<AppState>, pod_ip: &str) -> bool {
    match exec_on_pod(state, pod_ip, "tasklist /NH | findstr rc-agent", 5000).await {
        Ok((_, stdout, _)) => stdout.contains("rc-agent"),
        Err(_) => false,
    }
}

/// Check if WebSocket channel is open for a pod.
async fn is_ws_connected(state: &Arc<AppState>, pod_id: &str) -> bool {
    let senders = state.agent_senders.read().await;
    match senders.get(pod_id) {
        Some(sender) => !sender.is_closed(),
        None => false,
    }
}

/// Check if lock screen HTTP server is responsive on the pod.
async fn is_lock_screen_healthy(state: &Arc<AppState>, pod_ip: &str) -> bool {
    let cmd = r#"powershell -NoProfile -Command "try { $r = Invoke-WebRequest -Uri 'http://127.0.0.1:18923/health' -TimeoutSec 3 -UseBasicParsing; $r.StatusCode } catch { 0 }""#;
    match exec_on_pod(state, pod_ip, cmd, 8000).await {
        Ok((_, stdout, _)) => {
            let code: u32 = stdout.trim().parse().unwrap_or(0);
            code == 200
        }
        Err(_) => false,
    }
}

/// Check if a deploy has been cancelled (state set to Failed by CancelDeploy command).
async fn is_cancelled(state: &Arc<AppState>, pod_id: &str) -> bool {
    let deploy_states = state.pod_deploy_states.read().await;
    matches!(deploy_states.get(pod_id), Some(DeployState::Failed { .. }))
}

/// Deploy rc-agent to a single pod.
///
/// This is the main deploy executor. It runs as a tokio::spawn'd background task.
/// The caller (API endpoint or rolling deploy) should spawn this and return immediately.
///
/// Steps:
/// 1. Validate binary URL is reachable
/// 2. Kill rc-agent.exe
/// 3. Wait for process to die (poll every 2s, up to 10s)
/// 4. Delete old binary
/// 5. Download new binary
/// 6. Size check
/// 7. Write config
/// 8. Start new process
/// 9. Verify health (process + WS + lock screen)
pub async fn deploy_pod(
    state: Arc<AppState>,
    pod_id: String,
    pod_ip: String,
    binary_url: String,
) {
    // Step 0: Validate binary URL is reachable BEFORE killing old process
    tracing::info!("Deploy [{}]: validating binary URL: {}", pod_id, binary_url);
    match state
        .http_client
        .head(&binary_url)
        .timeout(Duration::from_secs(10))
        .send()
        .await
    {
        Ok(resp) if resp.status().is_success() => {
            tracing::info!("Deploy [{}]: binary URL reachable", pod_id);
        }
        Ok(resp) => {
            let reason = format!("Binary URL returned HTTP {}: {}", resp.status(), binary_url);
            set_deploy_state(&state, &pod_id, DeployState::Failed { reason: reason.clone() }).await;
            send_deploy_failure_alert(&state, &pod_id, &reason).await;
            return;
        }
        Err(e) => {
            let reason = format!("Binary URL unreachable: {} ({})", binary_url, e);
            set_deploy_state(&state, &pod_id, DeployState::Failed { reason: reason.clone() }).await;
            send_deploy_failure_alert(&state, &pod_id, &reason).await;
            return;
        }
    }

    // Step 1: Kill rc-agent.exe
    set_deploy_state(&state, &pod_id, DeployState::Killing).await;
    log_pod_activity(
        &state,
        &pod_id,
        "deploy",
        "Deploy Started",
        &format!("Binary: {}", binary_url),
        "deploy",
    );
    // taskkill may fail if not running — that is OK
    let _ = exec_on_pod(&state, &pod_ip, "taskkill /F /IM rc-agent.exe", 5000).await;

    // Step 2: Wait for process to exit
    set_deploy_state(&state, &pod_id, DeployState::WaitingDead).await;
    let mut dead = false;
    let max_polls = PROCESS_KILL_TIMEOUT_SECS / PROCESS_POLL_INTERVAL_SECS;
    for _ in 0..max_polls {
        tokio::time::sleep(Duration::from_secs(PROCESS_POLL_INTERVAL_SECS)).await;
        if is_cancelled(&state, &pod_id).await {
            return;
        }
        if !is_process_alive(&state, &pod_ip).await {
            dead = true;
            break;
        }
    }

    if !dead {
        let reason = format!(
            "Process still running after {}s of polling. File lock likely prevents binary replacement.",
            PROCESS_KILL_TIMEOUT_SECS
        );
        set_deploy_state(&state, &pod_id, DeployState::Failed { reason: reason.clone() }).await;
        send_deploy_failure_alert(&state, &pod_id, &reason).await;
        log_pod_activity(&state, &pod_id, "deploy", "Deploy Failed", &reason, "deploy");
        return;
    }

    // Step 3: Delete old binary (may fail if already gone — OK)
    let _ = exec_on_pod(
        &state,
        &pod_ip,
        "del /F C:\\RacingPoint\\rc-agent.exe",
        5000,
    )
    .await;

    // Cancellation check before download
    if is_cancelled(&state, &pod_id).await {
        return;
    }

    // Step 4: Download new binary
    set_deploy_state(&state, &pod_id, DeployState::Downloading { progress_pct: 0 }).await;
    let download_cmd = format!(
        "curl.exe -s -f -o C:\\RacingPoint\\rc-agent.exe {}",
        binary_url
    );
    match exec_on_pod(&state, &pod_ip, &download_cmd, 120_000).await {
        Ok((success, _stdout, stderr)) => {
            if !success {
                let reason = format!(
                    "Binary download failed: {}",
                    stderr.chars().take(200).collect::<String>()
                );
                set_deploy_state(&state, &pod_id, DeployState::Failed { reason: reason.clone() })
                    .await;
                send_deploy_failure_alert(&state, &pod_id, &reason).await;
                log_pod_activity(&state, &pod_id, "deploy", "Deploy Failed", &reason, "deploy");
                return;
            }
        }
        Err(e) => {
            let reason = format!("Download command failed: {}", e);
            set_deploy_state(&state, &pod_id, DeployState::Failed { reason: reason.clone() }).await;
            send_deploy_failure_alert(&state, &pod_id, &reason).await;
            log_pod_activity(&state, &pod_id, "deploy", "Deploy Failed", &reason, "deploy");
            return;
        }
    }
    set_deploy_state(
        &state,
        &pod_id,
        DeployState::Downloading { progress_pct: 100 },
    )
    .await;

    // Step 5: Size check
    set_deploy_state(&state, &pod_id, DeployState::SizeCheck).await;
    let dir_result = exec_on_pod(
        &state,
        &pod_ip,
        "dir C:\\RacingPoint\\rc-agent.exe",
        5000,
    )
    .await;
    match dir_result {
        Ok((_, stdout, _)) => match parse_file_size_from_dir(&stdout) {
            Some(size) => {
                if let Err(reason) = validate_binary_size(size) {
                    set_deploy_state(
                        &state,
                        &pod_id,
                        DeployState::Failed { reason: reason.clone() },
                    )
                    .await;
                    send_deploy_failure_alert(&state, &pod_id, &reason).await;
                    log_pod_activity(
                        &state,
                        &pod_id,
                        "deploy",
                        "Deploy Failed",
                        &reason,
                        "deploy",
                    );
                    return;
                }
                tracing::info!(
                    "Deploy [{}]: binary size OK ({} bytes)",
                    pod_id, size
                );
            }
            None => {
                let reason = format!(
                    "Could not parse binary size from dir output: {}",
                    stdout.chars().take(200).collect::<String>()
                );
                set_deploy_state(
                    &state,
                    &pod_id,
                    DeployState::Failed { reason: reason.clone() },
                )
                .await;
                send_deploy_failure_alert(&state, &pod_id, &reason).await;
                log_pod_activity(&state, &pod_id, "deploy", "Deploy Failed", &reason, "deploy");
                return;
            }
        },
        Err(e) => {
            let reason = format!("Dir command failed: {}", e);
            set_deploy_state(&state, &pod_id, DeployState::Failed { reason: reason.clone() }).await;
            send_deploy_failure_alert(&state, &pod_id, &reason).await;
            log_pod_activity(&state, &pod_id, "deploy", "Deploy Failed", &reason, "deploy");
            return;
        }
    }

    // Cancellation check before writing config
    if is_cancelled(&state, &pod_id).await {
        return;
    }

    // Step 6: Write config (generate from template based on pod number)
    // Extract pod_number from pod_id ("pod_3" -> 3)
    let pod_number: u32 = pod_id
        .strip_prefix("pod_")
        .and_then(|n| n.parse().ok())
        .unwrap_or(0);

    if pod_number >= 1 && pod_number <= 8 {
        let config_content = generate_pod_config(pod_number);
        let write_url = format!("http://{}:{}/write", pod_ip, POD_AGENT_PORT);
        let write_result = state
            .http_client
            .post(&write_url)
            .json(&serde_json::json!({
                "path": "C:\\RacingPoint\\rc-agent.toml",
                "content": config_content
            }))
            .timeout(Duration::from_secs(10))
            .send()
            .await;

        match write_result {
            Ok(resp) if resp.status().is_success() => {
                tracing::info!("Deploy [{}]: config written", pod_id);
            }
            Ok(resp) => {
                tracing::warn!(
                    "Deploy [{}]: config write returned HTTP {} -- proceeding with existing config",
                    pod_id,
                    resp.status()
                );
            }
            Err(e) => {
                tracing::warn!(
                    "Deploy [{}]: config write failed: {} -- proceeding with existing config",
                    pod_id,
                    e
                );
            }
        }
    }

    // Step 7: Start new rc-agent.exe
    set_deploy_state(&state, &pod_id, DeployState::Starting).await;
    let start_cmd = "cd /d C:\\RacingPoint && start /b rc-agent.exe";
    // start /b exits immediately (or times out) — both are OK
    let _ = exec_on_pod(&state, &pod_ip, start_cmd, 5000).await;

    // Step 8: Verify health (process + WS + lock screen)
    set_deploy_state(&state, &pod_id, DeployState::VerifyingHealth).await;

    for delay in VERIFY_DELAYS {
        tokio::time::sleep(Duration::from_secs(*delay)).await;

        if is_cancelled(&state, &pod_id).await {
            return;
        }

        let process_ok = is_process_alive(&state, &pod_ip).await;
        if !process_ok {
            continue; // process not yet started -- wait for next check
        }

        let ws_ok = is_ws_connected(&state, &pod_id).await;
        let lock_ok = is_lock_screen_healthy(&state, &pod_ip).await;

        if ws_ok && lock_ok {
            // Full health verified
            set_deploy_state(&state, &pod_id, DeployState::Complete).await;
            log_pod_activity(
                &state,
                &pod_id,
                "deploy",
                "Deploy Completed",
                &format!(
                    "Binary deployed and verified healthy after {}s",
                    delay
                ),
                "deploy",
            );
            // Reset to Idle after a brief delay so dashboard can show Complete
            tokio::time::sleep(Duration::from_secs(10)).await;
            set_deploy_state(&state, &pod_id, DeployState::Idle).await;
            return;
        }
    }

    // All verify delays exhausted without full health
    let process_ok = is_process_alive(&state, &pod_ip).await;
    let ws_ok = is_ws_connected(&state, &pod_id).await;
    let lock_ok = is_lock_screen_healthy(&state, &pod_ip).await;

    let reason = if !process_ok {
        "Process not running after start".to_string()
    } else if !ws_ok {
        "WebSocket not connected after 60s".to_string()
    } else if !lock_ok {
        "Lock screen not responsive after 60s".to_string()
    } else {
        "Health verification failed (unknown reason)".to_string()
    };

    set_deploy_state(
        &state,
        &pod_id,
        DeployState::Failed { reason: reason.clone() },
    )
    .await;
    send_deploy_failure_alert(&state, &pod_id, &reason).await;
    log_pod_activity(&state, &pod_id, "deploy", "Deploy Failed", &reason, "deploy");
}

/// Send an email alert for a deploy failure.
async fn send_deploy_failure_alert(state: &Arc<AppState>, pod_id: &str, reason: &str) {
    let subject = format!("[RaceControl] Deploy FAILED on {}", pod_id);
    let body = format!(
        "Deploy to {} failed.\n\nReason: {}\n\nTime: {}\n\nAction: Check pod manually or retry deploy.",
        pod_id,
        reason,
        Utc::now().format("%Y-%m-%d %H:%M:%S UTC"),
    );
    state
        .email_alerter
        .write()
        .await
        .send_alert(pod_id, &subject, &body)
        .await;
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── validate_binary_size tests ──────────────────────────────────────────

    #[test]
    fn validate_binary_size_at_threshold_ok() {
        assert!(validate_binary_size(5_000_000).is_ok());
    }

    #[test]
    fn validate_binary_size_above_threshold_ok() {
        assert!(validate_binary_size(5_000_001).is_ok());
        assert!(validate_binary_size(15_000_000).is_ok());
    }

    #[test]
    fn validate_binary_size_below_threshold_err() {
        assert!(validate_binary_size(4_999_999).is_err());
    }

    #[test]
    fn validate_binary_size_zero_err() {
        let result = validate_binary_size(0);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("too small"));
    }

    #[test]
    fn validate_binary_size_small_file_err() {
        // HTML error page saved as .exe
        assert!(validate_binary_size(1024).is_err());
    }

    // ── parse_file_size_from_dir tests ──────────────────────────────────────

    #[test]
    fn parse_file_size_normal_dir_output() {
        let output = " Volume in drive C is Windows\n Directory of C:\\RacingPoint\n\n03/13/2026  10:30 AM        15,234,567 rc-agent.exe\n               1 File(s)     15,234,567 bytes\n";
        assert_eq!(parse_file_size_from_dir(output), Some(15234567));
    }

    #[test]
    fn parse_file_size_file_not_found() {
        let output = "File Not Found\n";
        assert_eq!(parse_file_size_from_dir(output), None);
    }

    #[test]
    fn parse_file_size_empty() {
        assert_eq!(parse_file_size_from_dir(""), None);
    }

    #[test]
    fn parse_file_size_no_commas() {
        let output = "03/13/2026  10:30 AM        15234567 rc-agent.exe\n";
        assert_eq!(parse_file_size_from_dir(output), Some(15234567));
    }

    // ── deploy_step_label tests ─────────────────────────────────────────────

    #[test]
    fn deploy_step_label_killing() {
        let label = deploy_step_label(&DeployState::Killing);
        assert_eq!(label, "Killing old rc-agent process");
    }

    #[test]
    fn deploy_step_label_failed() {
        let label = deploy_step_label(&DeployState::Failed {
            reason: "binary too small".to_string(),
        });
        assert_eq!(label, "Deploy failed: binary too small");
    }

    #[test]
    fn deploy_step_label_downloading() {
        let label = deploy_step_label(&DeployState::Downloading { progress_pct: 75 });
        assert_eq!(label, "Downloading new binary (75%)");
    }

    #[test]
    fn deploy_step_label_complete() {
        let label = deploy_step_label(&DeployState::Complete);
        assert_eq!(label, "Deploy completed successfully");
    }

    // ── generate_pod_config tests ───────────────────────────────────────────

    #[test]
    fn generate_pod_config_contains_correct_pod_number() {
        let config = generate_pod_config(3);
        assert!(config.contains("number = 3"));
        assert!(config.contains("\"Pod 03\""));
    }

    #[test]
    fn generate_pod_config_contains_core_url() {
        let config = generate_pod_config(1);
        assert!(config.contains("ws://192.168.31.23:8080/ws/agent"));
    }

    #[test]
    fn generate_pod_config_contains_games() {
        let config = generate_pod_config(8);
        assert!(config.contains("[games.assetto_corsa]"));
        assert!(config.contains("[games.f1_25]"));
        assert!(config.contains("[ai_debugger]"));
    }
}
